prometheus-community/windows_exporter

- collectors/perf.go
As per the TODO list on the wiki, I added volume labels to the perf collector. I also added a whitelist/blacklist functionality similar to what is used in other exporters, defaulting to excluding the `_Total` "meta-counter".
By the way, shouldn't the collector be named something like logical_disk rather than perf?
> Perf: Add volume name label

- collectors/iis.go
- collectors/logical_disk.go
- exporter.go
This is a first draft of an IIS collector from `Win32_PerfRawData_W3SVC_WebService`. In contrast with other classes, this one actually exposes counters, so it was fairly straightforward.
Some sample output:
```
wmi_iis_non_anonymous_users_total{site="ASecondTestForTest"} 0
wmi_iis_non_anonymous_users_total{site="Default Web Site"} 0
wmi_iis_not_found_errors_total{site="ASecondTestForTest"} 1
wmi_iis_not_found_errors_total{site="Default Web Site"} 2
wmi_iis_rejected_async_io_requests_total{site="ASecondTestForTest"} 0
wmi_iis_rejected_async_io_requests_total{site="Default Web Site"} 0
wmi_iis_requests_total{method="COPY",site="ASecondTestForTest"} 0
wmi_iis_requests_total{method="COPY",site="Default Web Site"} 0
wmi_iis_requests_total{method="DELETE",site="ASecondTestForTest"} 0 …
```
> IIS collector

- appveyor.yml
This fixes the fact that AppVeyor currently does not upload releases even though they are tagged. Apparently the branch name is replaced by the tag name (in contraditiction with their examples...)
> Remove branch requirement for deployments, since it seems broken in combination with tags

- collector/cpu.go
- collector/logical_disk.go
- collector/wmi.go
- exporter.go
Some initial work on the cpu collector. I chose the [`Win32_PerfRawData_PerfOS_Processor`](https://msdn.microsoft.com/en-us/library/aa394317(v=vs.90).aspx) over `Win32_PerfRawData_Counters_ProcessorInformation` since it is more widely available (the latter was introduced in Windows 2008R2). 
A few notes: 
- There is a "total" cpu time exposed (should probably be removed before merging anyway, but I added it for reference initially), but I can't get it to match the other timings:
```bash
wmi_cpu_time_total{core="0",mode="idle"} 27154.335649999997
wmi_cpu_time_total{core="0",mode="interrupt"} 409.140625
wmi_cpu_time_total{core="0",mode="privileged"} 4150.9375
wmi_cpu_time_total{core="0",mode="total"} 28108.4375
wmi_cpu_time_total{core="0",mode="user"} 3325.8125
```
My total uptime was …
> Cpu collector

- appveyor.yml
It seems appveyor has been upgraded to have go 1.7.1 out-of-box.
so this patch simplifies appveyor.yml to remove the custom "install go 1.7" build step. should speed up CI by a few seconds
> simplify appveyor

- README.md
- collector/dns.go
This PR adds a collector for the Windows DNS Server.
There's not much documentation for this one, sadly. I've tested it on my work environment, and also set up a pair of VMs to test the zone transfer stuff (we don't use that) and it all _seems_ reasonable, but there may be some metrics that are actually overlapping (for instance `IXFRSuccessReceived` is _likely_ the sum of `IXFRTCPSuccessReceived` and `IXFRUDPSuccessReceived`, so I skipped it, but I was unable to make my systems actually generate non-zero values for those counters).
Naming is up for debate, I'm not super-pleased with a lot of the names. I've created a gist [here](https://gist.github.com/carlpett/f22ed6e8ea9dd7aa4f7291eaaa45b3ad) where the metrics, their labels and the included counters as well as some values from my …
> Add DNS server collector

- collector/system.go
…raw data doesnt change. fixes #40
> system: fix uptime calculation

- appveyor.yml
This PR adds a build matrix so that both x86 and amd64 versions are built. Fixes #47.
_Note: I don't have access to a git client at the moment, so this should be squashed as a PR-merge option to remove AppVeyor experimentation commits_
> Build both x86 and amd64 artifacts

- exporter.go
- exporter_test.go
Fixes #44.
By adding the placeholder `[defaults]` in the list sent to `-collectors.enabled`, the user can add extra collectors without having to keep the defaults enabled. This makes updates when having extra collectors enabled, since you no longer need to update the list with new default collectors. For example, our web servers currently have `-collectors.enabled "cpu,cs,iis,logical_disk,net,os,system"`, just to enable `iis`. When we update to the latest release which supports the `service´ collector, we need to update our configuration to benefit from it.
I wrote a few tests for the merging logic, but I'm not all that pleased with the amount of string juggling needed in the tests themselves. Any ideas for improvements?
> Add [defaults] placeholder support to collectors.enabled

- collector/net.go
prevent rolling while collecting on large network adapters.
> Win32_PerfRawData_Tcpip_NetworkInterface struct to uint64

- collector/os.go
Added a new metric called wmi_os_local_time to the exporter, with which OS time on Windows can be also scraped from Prometheus (and, for instance alerts can be generated when it does not match the time of the server). The metric also contains a label called time_zone in which the time zone on Windows is stored (and can be compared accordingly with any value in Prometheus).
> Added local_time metric with time_zone label to OS collector

- exporter.go
- vendor/github.com/prometheus/client_golang/prometheus/counter.go
- vendor/github.com/prometheus/client_golang/prometheus/desc.go
- vendor/github.com/prometheus/client_golang/prometheus/doc.go
- vendor/github.com/prometheus/client_golang/prometheus/gauge.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/histogram.go
- vendor/github.com/prometheus/client_golang/prometheus/http.go
- vendor/github.com/prometheus/client_golang/prometheus/observer.go
- vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_7.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/registry.go
- vendor/github.com/prometheus/client_golang/prometheus/summary.go
- vendor/github.com/prometheus/client_golang/prometheus/timer.go
- vendor/github.com/prometheus/client_golang/prometheus/untyped.go
- vendor/github.com/prometheus/client_golang/prometheus/value.go
- vendor/vendor.json
https://github.com/prometheus/client_golang/pull/214
Thanks for this package! 👍
> Use the new prometheus http API

- installer/build.ps1
WiX is now on GitHub, which means stable download urls. Yay!
> Update WiX download url

- exporter.go
Currently the `scrape_duration_seconds` metric is a summary. When trying to reason about #89, it is hard to look back in time to see if others have this problem as well, since we do not have the buckets. I see no real benefit in using a summary here, and think we should be using a histogram instead.
Probably we should be setting the `Buckets` option as well, rather than using the defaults. My lowest 0.5 quantile with the current summary is ~0.04s, so I would make an initial guess that something like `[0.01, 0.015, 0.03, 0.1, 0.15, 0.3, 1.0, 3.0, Inf]` would capture the interesting ranges with acceptable precision?
> Change scrape_duration_seconds to gauge

- collector/iis.go
- collector/wmi.go
Fixes #85.
This became a pretty large patch, which also involved a fair amount of copy/paste to restructure all the cache metrics. I _think_ I caught all of them, but would appreciate a careful look.
The collector is also getting quite big. We should consider having a way of splitting it into sub-collectors so it is not as unwieldy to navigate (from an end user perspective I don't think you'd want to switch parts on/off, so we should still have them all toggled by the `iis` flag).
Some previous changes seems to have been done without `go fmt`, so there are a few whitespace changes in unrelated parts as well.
> Implement IIS worker process and server cache classes

- installer/wmi_exporter.wxs
Fixes #99.
I opted to set the display name to just "WMI Exporter" rather than the arguable clearer "Prometheus WMI exporter" to avoid throwing people off who might be used to it being called wmi_exporter in the list. Opinions? Maybe too change-averse? :)
@lubyou
> Add DisplayName and Description to Windows service

- README.md
- collector/msmq.go
Add MSMQ collector - Win32_PerfRawData_MSMQ_MSMQQueue
Count message and size for both queueu and journal.
metrics:
`# HELP wmi_msmq_messagesin_journal_queue Count messages in queue journal`
`# TYPE wmi_msmq_messagesin_journal_queue gauge`
`wmi_msmq_messagesin_journal_queue{name="msk-fna\\am_q"} 435`
`# HELP wmi_msmq_messagesin_queue Count messages in queue`
`# TYPE wmi_msmq_messagesin_queue gauge`
`wmi_msmq_messagesin_queue{name="msk-fna\\am_mirror_queue"} 2303`
`# HELP wmi_msmq_bytesin_journal_queue Size of queue journal in bytes`
`# TYPE wmi_msmq_bytesin_journal_queue gauge`
`wmi_msmq_bytesin_journal_queue{name="msk-fna\\am_q"} 1.712848e+06`
`# HELP wmi_msmq_bytesin_queue Size of queue in bytes`
`# TYPE wmi_msmq_bytesin_queue gauge` …
> Add MSMQ collector

- .gitignore
- README.md
- collector/textfile.go
- exporter.go
- installer/wmi_exporter.wxs
This adds a slightly modified textfile collector from the official
node_exporter project.
> Bring the textfile collector over from node_exporter

- collector/hyperv.go
There are labels set on collection for the HyperVLegacyNetworkAdapter metrics, but those are not part of the metric `Desc`s. This PR adds those labels.
Fixes #192
> Fix missing label on HyperVLegacyNetworkAdapter

- collector/textfile.go
- collector/textfile_test.go
This PR removes all carriage return characters (`\r`) from input files in the textfile collector when they are read by the expfmt parser, since it does not support them.
Fixes #199
> Strip carriage-returns from textfile input

- collector/hyperv.go
This pull request adds the following two extra HyperV VM classes
* Win32_PerfRawData_Counters_HyperVVirtualStorageDevice
* Win32_PerfRawData_NvspNicStats_HyperVVirtualNetworkAdapter
This will give us the following metrics
// Win32_PerfRawData_Counters_HyperVVirtualStorageDevice
* VMStorageErrorCount 
* VMStorageQueueLength 
* VMStorageReadBytesPersec 
* VMStorageReadOperationsPerSec 
* VMStorageWriteBytesPersec
* VMStorageWriteOperationsPerSec
// Win32_PerfRawData_NvspNicStats_HyperVVirtualNetworkAdapter
* VMNetworkBytesReceivedPersec 
* VMNetworkBytesSentPersec
* VMNetworkDroppedPacketsIncomingPersec
* VMNetworkDroppedPacketsOutgoingPersec
* VMNetworkPacketsReceivedPersec
* VMNetworkPacketsSentPersec
> Add extra HyperV VM classes

- collector/iis.go
If the `dst_cache` slice is empty, the program panics when trying to access `dst_cache[0]`
added a `if len(dst_cache) > 0 {}` block around the use of that variable to prevent that panic.
closes https://github.com/martinlindhe/wmi_exporter/issues/225
> fix iis collector panic

- collector/mssql.go
found that I had one metric with an extra `s` in `_genstatss_`, making it
inconsistent with it's siblings.
> fix mssql metric name type

- collector/mssql.go
redordered functions so that the two functions that list available child collectors are next
to each other - should make it less likely to miss editing one of those
when adding additional wmi classes
also removed the 'filter' from the `mssqlFilterAvailableClassCollectors`
function as it's not filtering anyting.
> reorder functions

- collector/mssql.go
in the process of trying to build a grafana dashboard with "useful"
mssql metrics, I was looking around for what metrics might be useful and
came across an article of [15 SQL Server Performace Counters to Monitor](https://blogs.sentryone.com/allenwhite/sql-server-performance-counters-to-monitor/)
two of the suggested metrics are provided by the AccessMethod
class, which I was not yet capturing.
So I added metrics for the
Win32_PerfRawData_MSSQLSERVER_SQLServerAccessMethods class.
> add mssql accessmethod class

- collector/mssql.go
the only sql servers I have access to are using the default
`MSSQLSERVER` instance names.  I was contacted by someone using a
different instance name and it was failing.
Found 2 bugs in the code:
1) I was returning the default `MSSQLSERVER` as an instance even if it wasn't found in the registry
2) learned that the WMI class naming scheme for non-default instances
was not what I had coded. Changed to incorproate new knowledge.
> fix mssql for non-default sql instances

- collector/ad.go
- collector/cs.go
- collector/dns.go
- collector/iis.go
- collector/mssql.go
- collector/os.go
- collector/system.go
- collector/tcp.go
- collector/vmware.go
If a WMI query were to return an empty result set, trying to access an
element in the result set would result in a `panic: runtime error:
index out of range` error.
add logic to explicitly check if the result set size is 0 and return an
error rather than try to access an element of the result set.
Fixes https://github.com/martinlindhe/wmi_exporter/issues/240
> protect against emtpy wmi query result sets

- README.md
When using the wmi_exporter from the Windows command prompt (cmd) or from a .bat file, the '%' character in a wildcard query has to be escaped with another '%'.
> Clarified that the % character has to be escaped

- README.md
- collector/memory.go
- collector/os_memory.go
- docs/collector.memory.md
Initial commit of the Win32_PerfRawData_PerfOS_Memory collector module
I'm currently getting the following runtime error(s):
C:\Users\whiteas\go\src\github.com\martinlindhe\wmi_exporter>.\wmi_exporter --collectors.enabled
="os_memory"
wmi
os_memory
←[36mINFO←[0m[0000] Enabled collectors: os_memory                 ←[36msource←[0m="exporter.go:2
31"
←[36mINFO←[0m[0000] Starting WMI exporter (version=, branch=, revision=)  ←[36msource←[0m="expor
ter.go:242"
←[36mINFO←[0m[0000] Build context (go=go1.11.1, user=, date=)     ←[36msource←[0m="exporter.go:2
43"
←[36mINFO←[0m[0000] Starting server on :9182                      ←[36msource←[0m="exporter.go:2
46"
←[31mERRO←[0m[0008] failed collecting os_memory metrics:<nil> wmi: cannot load field "Name" into
a "string": unsupported type (<nil>) …
> Win32_PerfRawData_PerfOS_Memory module

- README.md
- installer/wmi_exporter.wxs
Added the `ENABLED_COLLECTOR_SERVICE_FILTERS` parameter to the MSI installer in order to allow specifying a custom service query (`collector.service.services-where`).
Example:
```
msiexec /i wmi_exporter-0.5.1-amd64.msi ENABLED_COLLECTORS="service" ENABLED_COLLECTOR_SERVICE_FILTERS="""Name LIKE 'sql%'"""
```
Overall this is a rough attempt (I'm not familiar with MSI/windows packaging) at addressing #170.
> MSI parameter - EXTRA_FLAGS

- collector/textfile.go
- collector/textfile_test.go
This relates to https://github.com/martinlindhe/wmi_exporter/issues/245#issuecomment-442875445 and expands on #285 
When textfiles in encodings like UTF16LE are encountered, a cryptic error complaining about metric names being in the wrong format will be given. Of course, if a UTF16 file is read as UTF8, they _look_ like they're interspersed with null characters.
This PR causes these inputs to error earlier, with a more useful user-friendly message.
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> textfile collector: Ensure that only UTF8 textfiles are parsed

- collector/ad.go
- collector/cpu.go
- collector/cs.go
- collector/dns.go
- collector/hyperv.go
- collector/iis.go
- collector/logical_disk.go
- collector/memory.go
- collector/msmq.go
- collector/mssql.go
- collector/net.go
- collector/net_test.go
- collector/netframework_clrexceptions.go
- collector/netframework_clrinterop.go
- collector/netframework_clrjit.go
- collector/netframework_clrloading.go
- collector/netframework_clrlocksandthreads.go
- collector/netframework_clrmemory.go
- collector/netframework_clrremoting.go
- collector/netframework_clrsecurity.go
- collector/os.go
- collector/process.go
- collector/service.go
- collector/system.go
- collector/tcp.go
- collector/vmware.go
- exporter.go
- exporter_test.go
Obviously this isn't totally necessary, as it only makes sense to build this on Windows, but there's at least one collector (`textfille`) that has no Windows-specific dependencies, so can be built (and tested!) on other OSes.
I found this useful while testing #293, so I didn't have to fire up a Windows VM to test changes 😉
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> Adding windows build constraints

- README.md
- docs/README.md
This updates the primary README with missing links to the .NET framework collectors and adds the link to `memory` collector to the `docs/README`
> Update main README and docs/README

- collector/msmq.go
A warning is logged to event viewer when a where clause is provided - that should, in fact, lower down the results, so the condition had to be inverted.
> msmq - incorrect condition to log a warning

- collector/cpu.go
@martinlindhe Would you mind taking a look at this? My thought was I currently see 
```# HELP wmi_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
wmi_cpu_time_total{core="0",mode="dpc"} 1072.765625
wmi_cpu_time_total{core="0",mode="idle"} 1.6088626299490498e+07
wmi_cpu_time_total{core="0",mode="interrupt"} 1541.28125```
```
When I'd expect
```# HELP wmi_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
wmi_cpu_time_total{core="0",mode="dpc"} 1072.765625
wmi_cpu_time_total{core="0",mode="idle"} 1.6088626299490498e+07
wmi_cpu_time_total{core="0",mode="interrupt"} 1541.28125```
> Counter metrics should be exposed as counter rather than gauge

- README.md
- collector/thermalzone.go
- docs/collector.thermalzone.md
For issue #73 This PR adds a go file for ThermalZoneInformation that was autogenerated by New-Collector.ps1
> Added thermal zone information and documentation

- README.md
- collector/container.go
Reverts martinlindhe/wmi_exporter#364. The name property did not actually contain the name, and the property is being deprecated in hcsshim. See discussion in #357.
> Revert "Add container_name label to container collector"

- appveyor.yml
- exporter.go
Depends on #335.
This implements a rough abort after a timeout, so the scrape can return even if WMI has hung for some collectors (eg #89, #270).
I'm not super happy about the implementation, it feels like a mess of interleaved goroutines that are not easy to understand. Tried a few variations of using the normal `context`, but it also had a lot of them. 
Happy for suggestions. Maybe the main `Collect` function should be rewritten.
> Abort scrapes after configurable timeout

- tools/collector-generator/New-Collector.ps1
There is an issue with New-Collector.ps1
When you're trying to create collector from WMI class containing single Perfomance Counter generated JSON output is mailformed in the members definition section. Instead of array it has object definition which breaks template processing with error:
```
panic: json: cannot unmarshal object into Go struct field TemplateData.Members of type []main.Member
goroutine 1 [running]:
main.main()
C:/Users/ipoly/Desktop/wmi_exporter-master/tools/collector-generator/generate-collector.go:29 +0x4d9
can't load package: package main:
..\..\collector\win32_perfrawdata_mssqlsqlexpress01_mssqlsqlexpress01sqlerrors.go:1:1: expected 'package', found 'EOF'
```
An example of such WMI Class is [Win32_PerfRawData_MSSQLSERVER_SQLServerSQLErrors …
> Fix collector creation issue

- .gitignore
- collector/mssql.go
- docs/collector.mssql.md
Pull request changes:
+ Add support for [Transactions counters](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-transactions-object)
+ Fix wrong counter name for errors count (#370). I forgot to push changes, sorry :(
Also I'm not pretty happy with some counter names:
```
transactions_nonsnapshot_version_active_total
transactions_snapshot_active_total
transactions_active_total
transactions_update_snapshot_active_total
```
If follow the original microsoft naming pattern, they should be called
```
transactions_nonsnapshot_version_transactions
transactions_snapshot_transactions
transactions_transactions
transactions_update_snapshot_transactions
```
It's again a bit redundant, so I replaced the `transactions` suffix with `active_total` which is more …
> Add support for MSSQL Transactions counters

- exporter.go
A crucial `close` was dropped during a refactor of #335, leading to a channel+goroutine leak. This PR closes the channel and resolves both leaks.
> Fix goroutine leak

- README.md
- collector/logon.go
- docs/collector.logon.md
This PR introduces a new collector that tracks the number of logon sessions on a Windows device, by status.
The [Win32_LogonSession](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-logonsession) class only exposes logon session data, so this collector could possibly be merged into an existing collector.
Let me know if any changes are necessary.
> Export logon sessions metric

- collector/container.go
Fixes #391 
The build tag was added to make building without access to a gcc toolchain easier, but for some reason it seems to not be enabled during CI either. It should be put back, but to fix the immediate problem (the `container` collector hasn't been built into 0.8.x) let's just remove it.
> Remove cgo build tag from container collector

- docs/collector.textfile.md
After adding the `role.prom` file on Windows on around 15 virtual machines, we discovered that if we omit to insert an empty line feed at the end of the file, Prometheus won't get metrics from the virtual machine. Adding a new line fixes the issue and immediately start gathering metrics for the virtual machine.
> Added a required detail for the .prom file to work properly

- README.md
- collector/adfs.go
- docs/README.md
- docs/collector.adfs.md
Perflib is used to collect base AD FS performance counters.
A subset of the total performance counters has been added, but more will
likely be added in the future.
Documentation for the AD FS counters is poor. As such, some counters
have been omitted until their nature can be interpreted.
> Add adfs collector

- collector/tcp.go
Resolves #407
While the ConnectionsEstablished property in the
Win32_PerfRawData_Tcpip_TCP class is listed as a counter, real-world
metric values have been shown to increase *and* decrease.
Documentation for the property states "Number of TCP connections for
which the **current** state is either ESTABLISHED or CLOSE-WAIT" which
would imply the metric is a gauge.
No other class properties have shown this behaviour.
> Set tcp_connections_established to gauge type

- collector/adfs.go
Perflib ADFS only returns a single data result, so looping over data is
unnecessary
> ADFS: explicitly use first perflib result

- collector/system.go
- docs/collector.system.md
Migrate system collector to perflib. Perflib output is a bit nicer as `SystemUpTime` no longer needs to be calculated.
> Use perflib for system collector

- collector/net.go
- docs/collector.net.md
As with the memory collector, this is a very straightforward conversion.
> Use perflib for net collector

- README.md
Currently the last build sets that build status badge in the README. It should just show the state of master, not some random PR.
> Build badge should only reflect master

- collector/os.go
- docs/collector.os.md
I'm pretty sure I've seen an issue or PR with that before, but it would be really cool to have this info as a metric, similar to `wmi_exporter_build_info` since I really don't want another PowerShell script running, just this shiny exporter.
I could also split these in two metrics, but in my opinion they belong together and would just waste space.
> Add product name & version to os collector

- collector/cs.go
- docs/collector.cs.md
This can be useful for building grafana dashboards with dropdowns for multiple hosts.
Or for managed instances of Prometheus where the user is not able to add labels via config.
It is built in a similar way as node_exporter already does it with its uname metric.
Fixes #409 #160 #454
> Add collector for hostname information

- collector/mssql.go
- docs/collector.mssql.md
Resolves #250
Continuation of https://github.com/martinlindhe/wmi_exporter/pull/352 as this contribution seems to be abandoned.
> WIP: Implement mssql base counters

- collector/cs.go
The wmi lib does some type checking for nil values.
Use a pointer as a workaround for that.
fixes #475
> Fix cs collector crashing when running on a domain joined machine

- .promu.yml
Fixes #477 
After the change to Go modules and removing the vendor folder, the path we write the version info into changed, but the promu config was not updated.
> Fix versioning in binary

- collector/process.go
- docs/collector.process.md
This PR converts the process collector to use perflib rather than WMI. Without filters, it speeds up collection on my machine by 10-50x.
However, since the current implementation has filtering based on WQL, which we cannot support for perflib, this is a breaking change. I changed the flags to match what we have in eg `logical_disk`, with regexp white/blacklists.
> BREAKING: Convert the process collector to use perflib

- exporter.go
This PR removes the redirect from any unhandled path to /metrics. This behaviour has been with us since the beginning, but I'd like to finally remove it. 
This will break any existing installs that has assumptions about this, but do not set the `--telemetry.path` flag to whatever path they use.
> BREAKING: Remove redirect from unknown paths to /metrics

- README.md
- docs/collector.process.md
Since PR #489 `--collector.process.processes-where` no longer works, changing example in `README` to use `--collector.process.whitelist` with regexp.
Also expand docs for process filter regexp a little bit.
> Fix README for process whitelist and expand docs

- collector/adfs.go
The adfs collector doesn't register the perflib dependency after the `registerCollector` refactoring in #461.
Fixes #503
> adfs collector missing dependency

- collector/dhcp.go
- docs/README.md
- docs/collector.dhcp.md
Unfortunately perflib does not expose scope statistics
(DhcpServerv4ScopeStatistics), and WMI queries to this class don't
appear to be possible with the stackexchange/wmi module.
> Add dhcp collector

- collector/service.go
- docs/collector.service.md
I have added the `wmi_service_info` metric to the service collector including `display_name` and `process_id` of the service.
This labels would make service troubleshooting easier since service explorer shows DisplayName in the columns and the pid help to identify the running process  
I tested this in Windows server 16
#514
> add wmi_service_info metric with display_name and pid labels

- tools/collector-generator/New-Collector.ps1
This is somewhat related to https://github.com/martinlindhe/wmi_exporter/issues/522
Where I ran into issues with the generator. I tried to run it in Powershell 7.0.1 but found out that Get-WMIObject is no longer supported as Powershell 7 is based on .Net Core and .Net Core does not support WMI. We will have to use Get-CimInstance instead.
> Replace Get-WMIObject with Get-CimInstance for PS7 support

- README.md
> Fix README AppVeyor links

- collector/service.go
- docs/collector.service.md
Adding support for the `startName` (the name of the service account) creating the service.
- In case it is not available the lablel is left empty
Quoting from [the documentation](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-service?redirectedfrom=MSDN) the explanation of the added label
>StartName:
>Account name under which a service runs. Depending on the service type, the account name may be in the form of "DomainName\Username" or UPN format ("*Username@DomainName*"). 
>The service process is logged by using one of these two forms when it runs. If the account belongs to the built-in domain, then ".\Username" can be specified. For kernel or system-level drivers, StartName contains the driver object name (that is, "\FileSystem\Rdr" or "\Driver\Xns") which the I/O …
> feat (service): added support for service StartName

- collector/fsrmquota.go
The actual collector struct was accidentally removed in [c23ae31](https://github.com/prometheus-community/windows_exporter/pull/437/commits/c23ae3176f970208085713d06e152a968eae34d7), and this was somehow missed in the last review
> Revert fsrm struct removal

- exporter.go
Fixes #553
Just makes it available as plaintext without any really advanced features. 
I also cannot run the project locally due to needing GCC (And honestly i have no idea how to actually set that up)
> Add endpoint for getting the version of the binary

- collector/collector.go
- collector/mssql.go
The perflib-based access code replaces WMI and is substantially more efficient
and stable, leading to fewer collection timeouts in the mssql collector.
> Use perflib to gather metrics in the mssql collector

- docs/collector.mssql.md
`windows_mssql_locks_lock_timeouts` and
`windows_mssql_locks_lock_timeouts_excluding_NOWAIT` metrics have
exchanged descriptions.
According to
https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-locks-object
---
Lock Timeouts     | Number of lock requests per second that
(timeout > 0)/sec | timed out, but excluding requests for NOWAIT locks.
---
Lock Timeouts/sec | Number of lock requests per second that timed
| out, including requests for NOWAIT locks.
---
Metrics gathered are correct but descriptions are exchanged.
Signed-off-by: Alexey Shumkin <Alex.Crezoff@gmail.com>
> Fix metrics description

- README.md
- installer/windows_exporter.wxs
I was looking for a way to limit the Windows Firewall exception (added by the installer) to the remote IP address of our prometheus server to prevent uninvolved systems from accessing the metrics endpoint. This could also be of interest to other users who want to roll out windows_exporter on a large number of machines (e.g. SCCM).
I've never used WiX before but found the `<fw:RemoteAddress>` tag and added a CLI property. I have successfully tested the following cases:
- `msiexec /i <path-to-msi-file> REMOTE_ADDR=<ip-address-1>`: Adds one IP address to `Remote IP address` in FW rule
- `msiexec /i <path-to-msi-file> REMOTE_ADDR=<ip-address-1>,<ip-address-2>`: Adds two IP addresses to `Remote IP address` in FW rule
- `msiexec /i <path-to-msi-file>`: Leaves the option `Any IP address` …
> Enable the use of remote ip addresses in Windows Firewall exception

- installer/windows_exporter.wxs
With afterInstallExecute, the old installation is only removed after the new one is finished, which has led to some users seeing the new version failing to start, leading to the install rolling back. afterInstallInitialize, in contrast, uninstalls before the new installation.
Fixes #558
> Change upgrade phase

- .gitignore
- appveyor.yml
- versioninfo.json
This PR adds versioninfo generation for the .exe to the build steps, meaning checking the file properties will now look like this:
I also had a moment of inspiration when I saw the field for the icon, so I also threw together the below and if people think it looks okay, it will be the icon for the exe and in Add/Remove programs:
(@brian-brazil - I couldn't find any separate license/usage guidelines for the Prometheus logo and my understanding is that this type of derivative work is fine, correct?)
Fixes #561
> Set Windows versioninfo on build

- collector/tcp.go
- docs/collector.tcp.md
Using perflib is substantially faster and more reliable than using WMI to
retrieve Windows performance counter data.
TCP over IPv6 is distinguished from IPv4 traffic by means of an "af" label
to denote the address family, which will be "ipv4" for TCP over IPv4,
corresponding to the TCPv4 performance object, and "ipv6" for TCP over
IPv6, corresponding to the TCPv6 performance object.
Signed-off-by: Michael Allen <MAllen@laserfiche.com>
> Convert the tcp collector to use perflib and support TCPv6 counters

- appveyor.yml
Fixes #629, by including bugfix for
https://github.com/golang/go/issues/35447
> Bump Go version from 1.13 to 1.15 for CI

- collector/mssql.go
- docs/collector.mssql.md
Change also renames metric to avoid confusion, so will need to be mentioned as a breaking change for next release.
Fixes #634.
> Set mssql transactions_active to Gauge.

- collector/hyperv.go
Apparently the format of the WMI object names returned for Hyper-V Virtual Processors doesn't always follow assumptions, leading to a panic. This PR changes this to a warning and a skip, to follow how the Host CPU metrics works. 
At a later point it would be good to discuss if this should be a failure instead.
Fixes #613
> Fix panic in HyperV collector on input format mismatch

- README.md
- collector/time.go
- docs/collector.time.md
Will resolve #532.
Note that despite testing the collector on a Windows 10 device with the NTP client enabled, I have not noted any change in the `windows_time_clock_frequency_adjustment_ppb_total` metric. Further testing of this metric by others would be welcome.
> Add Windows Time Service collector

- collector/collector.go
- collector/exchange.go
- docs/collector.exchange.md
related to #614 and #569 
The flag enables the windows_exporter to work with different exchange installations where not all performance counters are available. Detecting the installed roles would be even nicer, but is much more work. Either way this is a nice way of customizing the exporter.
As a side effect of this PR, the order in which the collectors are called is now fixed. As a result, if one of the sub collectors fails the returned metrics are now consistent.
> adds whitelist for exchange collectors

- installer/windows_exporter.wxs
This appears to fix service startup issues on certain systems, eg #637. Possibly also #627, #599, #544.
> Add service dependency on wmiApSrv

- README.md
- config/config.go
- config/flatten.go
- config/flatten_test.go
- docs/example_config.yml
- exporter.go
- go.mod
- go.sum
Initial implementation for configuration file support in windows_exporter.
Currently, the exporter supports reading from multiple YAML configuration files specified with the argument `--config.files=file1.yml,file2.yml`.
Values defined in these configuration files have a higher priority than values defined via command line arguments.
This will need testing and documentation once we're happy with the method/syntax of reading the files, and the config file structure.
Once merged, this will resolve #600.
> Configuration files

- exporter.go
FIxes #648.
I also tried the approach we initially discussed, passing the `app` to the collector package, by having a `registerFlags(regFn func(app *kingpin.Application))` in the collectors package and having each collector call that as part of `init`. That ended up being a lot less clear in my opinion, however (since flag variable definition and actual instantiation need to be split into the registration function and a var block).
> Fix collector flags not being registered

- README.md
- collector/smtp.go
- docs/README.md
- docs/collector.smtp.md
This implements an IIS SMTP Collector, exposing metrics for each SMTP virtual server configured on server.
As I don't have access to an in-use SMTP server at my work, I've downloaded the Windows Server 2019 evaluation ISO and installed the SMTP server on it. As such, the metrics aren't tested, and I can't confirm if their type (gauge/counter) is correct. This will need to be tested before it is merged.
Resolves #654
> Add SMTP collector

- Makefile
- appveyor.yml
- tools/e2e-output.txt
- tools/e2e-textfile.prom
- tools/end-to-end-test.ps1
Add an end-to-end testing script for use in CI, to compare changes in windows_exporter output.
I've tested this in a local Windows 10 VM, so I'm unsure how Appveyor would handle this.
A downside of this change is that the `e2e-output.txt` file would need to be modified on any metric change to the default exporters.
> End-to-end testing script

- collector/time.go
- docs/collector.time.md
Windows Server 2016 or newer is required for the collector, as the
perflib counters were not exposed in previous versions.
Resolves #658
> Document version requirement for time collector

- collector/dns.go
Metric is a gauge and therefore should not have the "total" suffix.
Resolves #284
> Remove "total" suffix from dns_memory_used_bytes

- docs/collector.net.md
The docs call the metric `windows_net_packets_outbound_discarded` but it is exported as `windows_net_packets_outbound_discarded_total`
https://github.com/prometheus-community/windows_exporter/blob/b9b60f1ea0e6c66314761f74b006814241cbe2ba/collector/net.go#L72-L77
> Use correct metric name for windows_net_packets_outbound_discarded

- collector/container.go
This updates the `container_id` label for the metrics reported by the container [collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.container.md) to use the owner ref which is set by docker and containerd respectively.
When running the windows_exporter with the `container` collector running with a containerd runtime the output of the metrics prefixes the metrics `container_id` label with `docker://` but it should be `containerd://` to match other tooling.
Current output:
```
windows_container_available{container_id="docker://130d82553c53d017649b7115a4e58a8007eef0641ce8804bfb6eb7dcc70ef18b", instance="10.240.0.65:5000", job="windows-exporter"}
```
If you use hcsdiag list on the host to see the owner ref it specifies the containerd shim as the …
> Set container collector prefix based on owner property

- README.md
- collector/cpu_info.go
- docs/collector.cpu_info.md
The cpu_info collector exposes a single metric per socket with some information on installed CPUs, somewhat like the node_cpu_info metric from node-exporter.
> Add a cpu_info collector

- collector/dfsr.go
- collector/smtp.go
`init()` causes warnings to be emitted despite collectors not being enabled.
> Move experimental warnings from init()

- docs/collector.tcp.md
I corrected a metric from counter to gauge.
You can see on line 129 in /collector/tcp.go that it should indeed be a gauge.
> Typo in tcp doc

- appveyor.yml
Nested directories caused issues with promu checksum output, causing
user checks of the sha265sums.txt file to fail as the filenames did not
match.
Resolves #756, #504
> CI: Output artifacts in single, flat directory.

- collector/msmq.go
msmq collector would only collect from a hard-coded "Computer
Queues" queue. Removal of filter allows other queues to be queried with
the collector.msmq.msmq-where flag.
Resolves #769
> Remove hard-coded "Computer Queues" filter

- headers/sysinfoapi/sysinfoapi.go
This corrects the layout of the SystemInfo structs which previously had a field that was too small, causing the struct to return the wrong values after being modified by the WinAPI function. 
Signed-off-by: Ben Ridley <benridley29@gmail.com>
> Correct layout of SystemInfo structs

- docs/collector.container.md
Added a 'data source' field to specify hcsshim of Host Compute Services in Hyper-V is used.
Fixes #776
> Fixes #776

- collector/net.go
- docs/collector.net.md
- tools/e2e-output.txt
From https://prometheus.io/docs/practices/naming/:
To avoid confusion combining different metrics, always use bytes, even
where bits appear more common.
Fixes #800
> Export CurrentBandwidth as bytes

- collector/textfile.go
- collector/textfile_test.go
> Fix textfile crashes with duplicate metrics

- collector/service.go
- Correct closing of service handler that was causing a memory increase over time since there were handlers kept on the heap.
@breed808, this is a fix for the feature we added on this PR https://github.com/prometheus-community/windows_exporter/pull/812.
> Service Api collection close servicehandler to avoid memory leak

- collector/iis.go
- docs/collector.iis.md
The IIS collector was constantly timing out on our servers, due to WMI being slow and unreliable. This change gathers all of the same metrics, but using Perflib instead of WMI, with a significant performance boost.
> Collect IIS metrics using Perflib

- exporter.go
Fixes:  #856
When working on https://github.com/prometheus-community/windows_exporter/pull/581#issuecomment-962050709 I got the error `time="2021-11-05T00:18:54Z" level=error msg="Failed to start service: The service process could not connect to the service controller." source="exporter.go:337"`
It was not running as a service so it should not fall into this code path.  I found https://pkg.go.dev/golang.org/x/sys/windows/svc#IsAnInteractiveSession was depreciated so made the switch.
> use IsWindowsService to detect if running as service

- .github/dependabot.yml
Bot will submit PRs when new dependency versions are detected,
preventing dependencies from becoming out-of-date.
> Add Dependabot dependency tracking

- collector/textfile.go
This PR fixes the default path for textfile collector. The previous implementation returned the full exe path, producing lots of error message:
> "Error reading textfile collector directory "C:
Program Files\\windows_exporter\\windows_exporter.exe
textfile_inputs": open C:\Program Files\windows_exporter\windows_exporter.exe\textfile_inputs: The system cannot find the path specified."
> Fix default path for textfile collector

- collector/iis.go
Allows the following metrics to be exposed again, they had disappeared after the migration to perflib :
- worker_request_errors_total
- worker_current_websocket_requests
- worker_websocket_connection_accepted_total
- worker_websocket_connection_rejected_total
Fix Issue #835
> fix: add missing metrics for IIS version >= 8

- installer/windows_exporter.wxs
Explicit setting of listening port in the service definition causes port
setting in configuration file to be ignored.
Exporter already defines a default port (9182) if one is not specified,
so no impact from this change is anticipated.
Resolves #881
> Remove explicit LISTEN_PORT from MSI installer

- appveyor.yml
Old token was using outdated format ([see Github post](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats)), triggering email alerts.
> Update CI token

- collector/textfile.go
Loop was erroneously creating duplicate `windows_textfile_mtime_seconds`
metrics, causing the exporter to return a HTTP 500 error and no metrics
from any collector.
Resolves #899
> Move textfile mtime metric from loop

- .github/workflows/ci.yml
Hi @carlpett @breed808,
This add a GH Action for checking spelling issues detected by codespell. As I fixed all of them already at #892, this will prevent us for adding new ones.
> codespell: add GH Action for checking spelling issues

- README.md
Hi @carlpett @breed808,
This replace the old AppVeyor badge by the new one for GH Actions.
> README.md: Replace the AppVeyor badge with the GH Actions one

- collector/tcp.go
- docs/collector.tcp.md
Hi @breed808 @carlpett,
This fix all `counter metrics should have "_total" suffix` issues reported by promtool. See #659.
NOTE: This must be noted as breaking changes in the CHANGELOG for the next version.
> Fix counter metrics should have "_total" suffix issue

- installer/windows_exporter.wxs
Resolves #911 which was introduced by 45e9357a.
This is due to the exporter only using the default port if no LISTEN_ADDR
**and** no LISTEN_PORT is defined.
> Port should default to 9182 if not defined

- collector/adfs.go
- docs/collector.adfs.md
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Reformat adfsCollector struct
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Add metrics to ADFS collector documentation
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Update ADFS collector with useful queries and links to documentation
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Remove bad table formatter
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Reformat ADFS collector using gofmt
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
Fix ADFS Config and Artifact DB Query time metrics
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
> Add more ADFS metrics from `AD FS` CounterSet

- .github/workflows/ci.yml
Dependency upgrade has resulted in [github.com/prometheus/client_golang](https://github.com/prometheus/client_golang) being upgraded from v1.11.0 to v1.12.0 prior to end-to-end test.
This new release introduces new `go_*` metrics, causing the test to fail on the unexpected output.
This fixes CI failures with recent PRs (#885 and #921).
I'll add the expected output in another PR once Dependabot picks up the new `client_golang` release.
> Don't upgrade dependencies when installing tools

- collector/iis.go
The IIS >= 8 metrics was updated two times by application and caused a fatal error. The purpose
of this fix is to update metrics one time by application.
Fixed #903
> fix: iis metrics greater than IIS v7

- collector/iis.go
Checks were removed in 82f17fd despite flags still being present.
Resolves #936
> Add missing whitelist/blacklist checks for IIS

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- README.md
- exporter.go
- kubernetes/kubernetes.md
- kubernetes/windows-exporter-daemonset.yaml
- kubernetes/windows-exporter-podmonitor.yaml
Kubernetes now has support for [HostProcess Containers](https://kubernetes.io/blog/2021/08/16/windows-hostprocess-containers/) so this is a continuation of https://github.com/prometheus-community/windows_exporter/pull/581 using HostProcess containers
Requirements:
- Kuberentes 1.22+
- containerd 1.6 Beta+
- WindowsHostProcessContainers feature-gate (currently in alpha in 1.22 going beta in 1.23) turned on for kube-apiserver and kubelet if using Kubernetes 1.22
> Add HostProcess Container Configuration for k8s

- collector/container.go
- docs/collector.container.md
Add storage metrics for windows container from container's storagestats of hcsshim.
reference: [windows container's Statistics struct](<https://github.com/microsoft/hcsshim/blob/master/test/vendor/github.com/Microsoft/hcsshim/internal/hcs/schema1/schema1.go#L188>)
Example metrics:
```
windows_container_storage_read_count_normalized_total{container_id="docker://0a1d78f90178bbfd80aa49572a60868c2421899121c60394938ca2e830860a7c"} 5088
windows_container_storage_read_count_normalized_total{container_id="docker://1a4e8d1fdbe62dfa8638cf90704f72d9a199e3afccfc1b36d364a96fb72577ad"} 1213
windows_container_storage_read_count_normalized_total{container_id="docker://38c1eb0b679a9dcfe2ab259617b653740241caaf8b6018770b2977dcb8762ec3"} 897
windows_container_storage_read_count_normalized_total{container_id=" …
```
> feat: add storage metrics for container collector

- kubernetes/kubernetes.md
The docs don't render properly in Markdown due to missing closing code block.
> Fix formatting for kubernetes documentation

- collector/memory.go
- docs/collector.memory.md
Hi @carlpett @breed808,
This fixes some issues reported by `promtool`. See #659. 
Besides of that it extends the collector documentation from [wutils.com](https://wutils.com/wmi/root/cimv2/win32_perfformatteddata_perfos_memory/). Feel free to adjust any wording issue.
NOTE: This must be noted as breaking changes in the CHANGELOG for the next version.
NOTE2: After merging this, we could make the collector default enabled.
> Fix memory collector promtool metric issues

- .github/workflows/ci.yml
CI builds for #968 and #969 have been failing due to issues with the golangci-lint action and the `goversioninfo` tool installation.
This PR updates both the action and tool, and changes tool installation from `go get` to `go install`.
> Resolve recent CI issues

- README.md
- collector/scheduled_task.go
- collector/scheduled_task_test.go
- docs/README.md
- docs/collector.scheduled_task.md
- docs/example_config.yml
- go.mod
- go.sum
Adding a new collector called `scheduled_task` that can be enabled to provide metrics about registered tasks configured in the Windows Task Scheduler Service. ( #808 )
> Adding Scheduled Tasks Collector

- kubernetes/kubernetes.md
Previous `nanoserver` image did not have Powershell installed, causing
the init container to fail.
Resolves #961.
> Use `powershell` image for firewall init container

- exporter.go
replace these prometheus deprecated functions
> replace these deprecated functions

- collector/os.go
Inactive or missing paging file should not be cause for OS collector to
fail.
Instead, log the error and continue with OS collection.
Resolves #939
> Continue OS collector on absent paging file

- collector/mscluster_resourcegroup.go
UpdateDomain metric not exists as we can see in  https://docs.microsoft.com/en-us/previous-versions/windows/desktop/cluswmi/mscluster-resourcegroup, just removing from mscluster_resourcegroup.go
When execute windows_exporter.exe with this metric we get this error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xaad61d]
goroutine 66 [running]:
github.com/prometheus/client_golang/prometheus.NewConstMetric(0xc00009de30?, 0x2?, 0x3ff0000000000000?, {0xc000387730?, 0x1?, 0x1?})
C:/Users/ricar/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/value.go:88 +0x1d
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
C:/Users/ricar/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/valu …
> fix: remove UpdateDomain (mscluster-resourcegroup) 

- collector/iis.go
Collector would previously break from loop rather than skip nameless
entries, with the additional result of spamming event logs.
I wasn't able to re-open the PR in #985 due to the original branch being destroyed, so consider this a continuation of the discussion.
Resolves #975
> Skip missing IIS instances

- .github/workflows/ci.yml
Write permissions are required to upload release artifacts.
> Add content write permissions to GITHUB_TOKEN

- collector/service.go
Fix error preventing to collect certain restricted services when using the service collector in api mode "useApi".
Since the handler used sets by default SC_MANAGER_ALL_ACCESS when creating a service handler, in certain windows distributions and for certain services, it is not possible to open a connection to those services that are restricted.
Opening the service with GENERIC_READ fixes the issue.
This addresses https://github.com/prometheus-community/windows_exporter/issues/1037
Signed-off-by: Alvaro Cabanas <albanas@gmail.com>
> Fix Error "Service Access is denied" in service collector useApi 

- collector/hyperv.go
- docs/collector.hyperv.md
Add Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor WMI class to monitor Hyper-V Hypervisor Logical Processor. The class shows metrics for actual CPU utilization on hypervisor hosts.
This addresses https://github.com/prometheus-community/windows_exporter/issues/444
Example output:
```
windows_hyperv_host_lp_guest_run_time{core="0"} 4.288535665036e+12
windows_hyperv_host_lp_guest_run_time{core="1"} 3.8546816773e+11
windows_hyperv_host_lp_hypervisor_run_time{core="0"} 9.95114252719e+11
windows_hyperv_host_lp_hypervisor_run_time{core="1"} 2.50063864275e+11
windows_hyperv_host_lp_total_run_time{core="0"} 5.283649917755e+12
windows_hyperv_host_lp_total_run_time{core="1"} 6.35532032005e+11
```
> Add Hyper-V Hypervisor Logical Processor metrics

- exporter.go
- initiate/initiate.go
This PR attempts to resolve a long standing [issue](https://github.com/prometheus-community/windows_exporter/issues/551) with the windows service timing out when CPU is constrained on the host machine.
The underlying cause of this is due to how late the service initialization happens in the code due to it existing in main() which is the last part of code to be run during startup as per:
What we attempt to do here is call the windows service as early as possible by placing it in a separate package's init() at the top of the main packages import list causing it to occur as early in the process as possible
Originally I had also moved the initiation of logging into this same package however i ran into issues with double logging in event viewer so ill revisit this at a later date.
The benefit …
> fix Windows Service timeout during high CPU (eg. post Windows Update)

- collector/os.go
Adds major version, minor version, and build number as independent
labels when exporting OS info.
> Export extra version information

- docs/collector.os.md
Forgot to request the documentation change in the earlier PR.
Changes introduced in 46fa84f have exposed additional labels to the
os_build_info metric.
Resolves #1022
> Document recent changes to os_build_info metric

- collector/netframework_clrmemory.go
Fix bug for counting value PercentTimeinGC
From program `WEBMTest.exe` in class `Win32_PerfRawData_NETFramework_NETCLRMemory` I was found counter type
```
[DisplayName("% Time in GC"): ToInstance, countertype(537003008): ToInstance, 
perfindex(2606): ToInstance, helpindex(2607): ToInstance, defaultscale(0): ToInstance, 
perfdetail(100): ToInstance] uint32 PercentTimeinGC
```
The mapping for countertype(537003008) is *PERF_RAW_FRACTION*.
For Cooking Type MSDN has formula (100 * CounterValue) / BaseValue
[Article](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/ms974615(v=msdn.10)?redirectedfrom=MSDN#perf_raw_fraction
)
> fix PercentTimeinGC metric

- collector/iis.go
- docs/collector.iis.md
Added the WebService uptime metric in the iis collector. This metric is
a counter and counts up the seconds when the service is up. If the
service is stopped, the uptime is 0. Fixes #1058.
> Added WebService uptime metric in iis collector

- .github/workflows/ci.yml
- Makefile
Support for these builds will be "best effort" as the project maintainers have no access to ARM64 Windows installations at this time.
Resolves #957
> Add ARM64 builds to releases

- collector/scheduled_task.go
OLE objects must be manually cleared or released to prevent leaks. Note that these objects do not appear in the heap, so the pprof heap profiles aren't helpful in identifying OLE leaks.
Graph below shows exporter running with the `scheduled_task` collector enabled, with `curl` querying the metrics endpoint continuously. First part of graph is the exporter built from `master`, second part is the exporter built from this feature branch.
Resolves #1063
> fix: Remove memory leaks in scheduled_task

- installer/windows_exporter.wxs
Signed-off-by: Brandon Kauffman <bck01215@gmail.com>
> Compatibily with new flag web.listen-address

- exporter.go
Parsing the flags twice duplicates the value for slice flags, it seems other binaries (alertmanager, exporters) are using both flags and treat it differently, besides this dirty fix solving this issue in particular, a bigger refactoring is required.
The following scenarios were tested:
1) Setting the bind flag directly: `--config.file=config.yml --web.listen-address=":9099"` bind on `:9099`
2) No bind flag and config set + passed via flag:
```
config.yml:
web:
listen-address: :9183
--config.file=config.yml
```
bind on :9183
3) No bind flags and config flag = `--config.file=config.yml` - bind on default :9182
> Cleaning up listen addresses flags before parsing config file

- collector/cpu.go
- collector/perflib.go
- collector/perflib_test.go
- docs/collector.cpu.md
- tools/e2e-output.txt
This change adds 4 new CPU related metrics:
* process_mperf_total
* processor_rtc_total
* processor_utility_total
* processor_privileged_utility_total
and renames the existing process_performance to
processor_performance_total, since it was previously misunderstood and was unlikely to be have been useful without the above new metrics
The data sources for these are not particularly well understood, and the examples show that in some cases, arbitrary scaling factors are required to actually make them useful, but in my testing on hundreds of systems with a broad range of CPUs and operating systems from 2012r2 through to 2019 has proved out that we can use them to accurately display actual CPU frequencies and CPU utilisation as it is represented in taskmgr.
Things I don't particularly like …
> Add cpu metrics based on newer and more accurate perflib sources

- collector/logical_disk.go
- docs/collector.logical_disk.md
- tools/e2e-output.txt
Add LogicalDisk metrics
1. AvgDiskReadQueueLength
2. AvgDiskWriteQueueLength
> Add Avg logical disk RW Queue metrics

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/spelling.yml
`build` job was redundant for PRs and pushes to `master` branch, as `go build` is run in the e2e job.
Linting jobs only need to be run for code changes, and were unnecessarily extending CI duration for documentation changes.
CI duration for PRs has been reduced (10-16min -> 3.5min) by downloading binaries for tools rather than compiling from source
> Split CI/CD configuration

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/spelling.yml
checkout@v2 and go-setup@v2 both used a deprecated Node.js version (12)
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for context
> Update deprecated Github Actions

- .github/workflows/release.yml
* Release job had an incorrect URL configured for downloading the `promu` build tool.
* Wix build tool doesn't support ARM builds in the current version (3.11.0.1701); ARM MSI builds have been disabled.
> Fix CI release issues

- README.md
This had me running in circles because `ioutil.ReadFile` did not read the local file for me when running as a service (i.e. `config.yml` in the same folder as the `windows_exporter.exe`). I had to use absolute paths and additionally quote them.
> Added quote information for absolute paths

- README.md
Fix the documentation and code inconsistencies caused by the following commit. 
> https://github.com/prometheus-community/windows_exporter/commit/e9c594473c0b9b794422e8314bd58f92bcc5c2e6
> docs: fix documentation error

- exporter.go
- tools/e2e-output.txt
- tools/end-to-end-test.ps1
Introduces a new `--disable-exporter-metrics` to allow users to disable metrics included by the Prometheus client library (promhttp_*, process_*, go_*)
Resolves #1159
> feat: Allow default metrics to be disabled

- collector/diskdrive.go
- collector/init.go
Previous name did not match documentation and WMI class.
Resolves #1169
> fix!: Set correct diskdrive collector/metric name

- docs/example_config.yml
The file `example_config.yml` was not modified since v0.21.0 where `--telemetry.addr` was deprecated in favor of `--web.listen-address`.
This PR fix #1178.
> Fix telemetry.addr deprecated since v0.21.0

- collector/collector.go
- collector/dfsr.go
- collector/exchange.go
- collector/iis.go
- collector/init.go
- collector/logical_disk.go
- collector/msmq.go
- collector/mssql.go
- collector/net.go
- collector/process.go
- collector/scheduled_task.go
- collector/service.go
- collector/smtp.go
- collector/textfile.go
- exporter.go
This PR remove the fluent-style usage of kingpin by an dedicated instance of kingpin. This allow programs to embed windows_exporter and pass a customized kingpin instance to all collectors.
At the moment, its hard to embedded windows_exporter in an other application. While its possible to feed the `kingpin.CommandLine` instance outside from windows_exporter, there are conflicts with other exporters do the same.
PR tested in a Windows 10 client machine.
Example Code for injected collector configuration into the embedded windows_exporter instance:
```go
// toExporterConfig converts integration Configs into windows_exporter configs.
func (c *Config) toExporterConfig(app *kingpin.Application) {
app.GetFlag(collector.FlagDfsrEnabledCollectors).StringVar(&c.Dfsr.SourcesEnabled) …
```
> Remove fluent-style kingpin

- kubernetes/windows-exporter-daemonset-ws2022.yaml
Adding a yaml spec with an image supported on Windows Server 2022 nodes.
> Add yaml for WS2022 nodes

- collector/prometheus.go
- exporter.go
This is useful, if windows_exporter is embedded als library. Right now the collector is part of the main package and can not start separately.
Tested on a windows 10 client machine
> Move prometheus collector from main to collectors

- collector/iis.go
- collector/iis_test.go
Perflib often exposes duplicate IIS entries, suffixed with '#' and a number (I.E. iis_site_name#1).
These duplicate entries were causing the exporter to fail scraping due to duplicate metrics.
Resolves #1009
> fix: Ignore duplicate IIS entries from Perflib

- collector/hyperv.go
`windows_hyperv_vswitch_packets_sent_total ` is in the [docs](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.hyperv.md#metrics) but not being collected. This PR fixes the problem.
> fix: add missing vswitch packets_sent_total

- collector/terminal_services.go
On prod env (30 hosts with more than 40 cnx each), perflibTerminalServicesSession's names are reused and caused duplicated labels names.
use a map to maintain the known names and remove them.
> fix Terminal Service duplicate session names under load.

- README.md
- config/config.go
- exporter.go
As requested in #1207 I've added support for loading the config file either from a directory or a URL.
> Load config file from URL

- collector/container.go
- bugfix
- This fix ensures that network stats for containerd on Windows are successfully collected. Before this change, other container stats such as CPU and memory are successfully collected, but network stats are not being collected successfully when using containerd.
- The root cause is that the code for collecting network stats was originally written to work with dockershim which relies on HCS v1 schema. After dockershim removal as Kubernetes's container runtime, containerd adoption has increased and this error is more frequently encountered when using containerd as the runtime. containerd uses HCS v2 schema whereby the network stats need to be queried from the HNS component.
- https://github.com/prometheus-community/windows_exporter/issues/1129
- …
> Resolve issue preventing networking container stats from being sent to collector

- collector/iis.go
Default value prevented use of the new `collector.iis.site-include` flag.
Resolves #1254
> fix: Remove default value from deprecated IIS flag

- config/config.go
Fix for #1263, there was an unnecessary check with `url.ParseRequestURI`. If you throw in gibberish it'll fail anyways.
> fix: config file CLI argument for relative paths -> v0.23.1 

- collector/hyperv.go
- docs/collector.hyperv.md
Adds the following metrics for Hyper-V:
- `windows_hyperv_host_cpu_wait_time_per_dispatch_total`
- `windows_hyperv_vm_cpu_wait_time_per_dispatch_total`
This is one of key metrics for thoubleshooting overprovisioning, and was requested in https://github.com/prometheus-community/windows_exporter/issues/517#issuecomment-694710039.
> Add Hyper-V CPUWaitTimePerDispatch metrics

- docs/collector.adfs.md
Remaining metrics had the correct prefix (windows_adfs_) added.
Resolves #1270
> fix(docs): Remove duplicate ADFS metrics

- initiate/initiate.go
ok I was not entirely right with my theory in #1258. The real reason for the stop error is that this line is a nil pointer:
https://github.com/prometheus-community/windows_exporter/blob/8d615956074d9329eb33ece5ec19fc00a8d2af48/initiate/initiate.go#L34
This logline uses the global `logger` variable which is never set, it is only set inside of the `init()` function. Therefore the log attempt on line 34 will cause a nil pointer, the exe dies and no signal will be send and so on. 
This global variable was added with v23: https://github.com/prometheus-community/windows_exporter/commit/8509bc69a60bb6b608d390fabdf6e4d64b939b2e
Nevertheless, what I wrote in #1258 is also possible. I have tested with:
```go
loop:
for {
select {
case c := <-r:
switch c.Cmd {
case svc.Interrogate:
changes <- …
```
> fix: Windows service can't stop without an error

- collector/ad.go
- docs/collector.ad.md
A very handy metric to observe. If you hit your hard limit (5000 by default) connections start to drop off. Its a good indicator to know there is a bad LDAP Client connecting to your directory
> Add new counter LDAP Client Sessions

- collector/textfile.go
- collector/textfile_test.go
- docs/collector.textfile.md
- tools/textfile-test/duplicate-filename/file.prom
- tools/textfile-test/duplicate-filename/sub/file.prom
- tools/textfile-test/multiple-dirs/dir1/dir1.prom
- tools/textfile-test/multiple-dirs/dir2/dir2.prom
- tools/textfile-test/multiple-dirs/dir3/dir3.prom
- tools/textfile-test/multiple-dirs/dir3/dir3sub/dir3sub.prom
Regarding #1236 and more
Added Features:
- collect files from multiple paths
- walkDir func for all paths to collect files from subdirs
- new flag command `collector.textfile.directories`
About the `collector.textfile.directories` commmand:
For now it is possible to use `collector.textfile.directories`, `collector.textfile.directory` or both. They have the same functionality and in case both commands would be used, the dirs are concatenated. I am not sure if that is ok so lets discuss 😉
As soon all is settled, I'll update the docs - `collector.textfile.md` 😊
> Textfile collector: collect files from multiple paths

- collector/os.go
Regarding: #1300 
Added revision to windows_os_info. It was already there in the registry `SOFTWARE\Microsoft\Windows NT\CurrentVersion` which is already opened, just needed to grab it.
> feat(#1300): add revision to windows_os_info

- pkg/collector/exchange/exchange.go
- pkg/collector/iis/iis.go
- pkg/collector/logical_disk/logical_disk.go
- pkg/collector/msmq/msmq.go
- pkg/collector/net/net.go
- pkg/collector/process/process.go
- pkg/collector/scheduled_task/scheduled_task.go
- pkg/collector/service/service.go
- pkg/collector/smtp/smtp.go
- pkg/collector/textfile/textfile.go
- pkg/utils/utils.go
When trying to remove the fork grafana agent uses ran into an issue with some strings being nil via the config. Kingpin never allows this so it hasnt been an issue yet.
Created two wrapper methods to make it easier, I could have went with one new func and ! the call  but I think its cleaner to have two. I checked for any *string and *bool.
Tested the windows_exporter and the Grafana Agent using this without problem.
> Check for nil strings and include wrappers around each.

- pkg/collector/iis/iis.go
- pkg/collector/logical_disk/logical_disk.go
- pkg/collector/net/net.go
- pkg/collector/process/process.go
- pkg/collector/scheduled_task/scheduled_task.go
- pkg/collector/smtp/smtp.go
- pkg/collector/textfile/textfile.go
This PR removing deprecated flags (blacklist, whitelist) + deprecated flag on textfile collector.
Since our major version is still <1, the breaking change is acceptable. If not, we can postpone this.
> Remove deprecated flags: --collector.*.*-blacklist / --collector.*.*-whitelist

- .github/workflows/stale.yml
windows_exporter has a lot of opened issue with may not longer interest. I would like to cleanup some of the approx 300 issues and staled PRs.
This action uses https://github.com/actions/stale . After 90 days of inactivity, a post will be written from gh actions. After another 30 days of interactivity, the issue will be closed.
> CI: Add stale action

- README.md
Omission of the collector implied that setting `TEXTFILE_DIR` was sufficient to enable the collector, which is not true.
Resolves #1344
> fix(docs): Add textfile to enabled_collectors

- .github/workflows/release.yml
- installer/build.ps1
- installer/windows_exporter.wxs
As WiX v3 did not support ARM64 builds, I've upgraded it to v4 in the Github release action and build script. The bulk of the work was done with `wix convert`.
I've run the release action in my own fork to confirm the MSIs are built correctly, see https://github.com/breed808/windows_exporter/releases/tag/v0.24.1 for the artifacts. I've successfully tested the `amd64` MSI with some variables (`ENABLED_COLLECTORS`, `LISTEN_PORT` and `METRICS_PATH`); unfortunately I'm not in a position to test the `386` or `arm64` MSI packages.
Resolves #1293
> Add ARM64 MSI builds

- README.md
- docs/collector.smb.md
- pkg/collector/collector.go
- pkg/collector/config.go
- pkg/collector/map.go
- pkg/collector/smb/smb.go
- pkg/collector/smb/smb_test.go
Added new collector for SMB Server
Collector collects 2 metrics:
- Current count of open files on the SMB Server(count of open files in shared folder)
- Current count of open session on the SMB Server(count of users connection to shared folder)
Thats metrics you can see on compmgmt.msc: Computer management -> Shared folders -> (Open files) and (Sessions)
> Add collector for SMB

- docs/collector.logical_disk.md
The naming convention for these metrics was different from that of the other collectors, so I renamed them following the same standard.
I also added a useful query to show the percentage of a specific volume in the instance
Signed-off-by: Isai Alejandro isai_alejandro@outlook.com
> metric name & useful query

- pkg/initiate/initiate.go
As explained in the closed PR #1372 this would be the shorthand fix for #1352.
Just to mention that @jkroepke suggested the it would be better to split the windows service stuff from the exporter itself and create two binaries. Like it is done in the https://github.com/grafana/agent/issues/3243 I also agree with that but this would be a bigger change and take more time to implement which I don't have at the moment.
So in the meantime this PR could fix the stop error and since there is only e little change in when the stop signal is sent, it should not re interduce some old behavior/issues like #1047 or #551.
I have tested this PR with default collectors enabled and windows 11 and windows server 2016 (I don't have more options just yet)
> fix(#1352): moving the stop signal after svc.Run()

- .github/workflows/release.yml
- Makefile
- installer/build.ps1
This PR removes x86 binary builds.
The x86 binary builds are broken, because Windows provides only int32 values for PerfCounter which leads into user error, if the value is higher than 32-bit integer.
I would like to remove build to reduce the maintenance efforts.
> Remove i386 builds

- .github/workflows/lint.yml
This PR uploads the windows_exporter.exe file from job lint as job artifact.
It give us the opportunity the ask different users, if PR like #1376 solves issues. Before this, users have build own exporter binaries which could be a blocker for inexperienced users.
> CI: Provide binary builds from GH actions

- README.md
- installer/windows_exporter.wxs
As announced in #1382 the according fix.
And I was wondering if deprecation warning here should be removed or changes since it argument is gone now?
https://github.com/prometheus-community/windows_exporter/blob/6ede10e29aeea4e5aa250a20ade395ce14058fdc/docs/collector.textfile.md?plain=1#L12-L16
> fix:(#1382): rename TEXTFILE_DIR to TEXTFILE_DIRS

- pkg/collector/process/process.go
as mentioned in #1390 the according PR.
> fix(#1390): global kingpin instead of app var

- README.md
Microsoft currently support Windows Server 2016 or newer, and Windows 10 and Windows 11 (21HR or later). Dropping support for end-of-life Windows Server versions will reduce maintenance overhead for project maintainers.
This removal of support is intended for the next major exporter release (v0.26.0).
> docs!: Remove support for EOL Windows versions

- pkg/collector/process/process.go
Process Collector Enable Worker Process Query Broken
Relating PR: [1062](https://github.com/prometheus-community/windows_exporter/pull/1062)
Error running:
.\windows_exporter.exe --web.listen-address "0.0.0.0:9183" --collectors.enabled "process" --collector.process.iis
Fixed the error:
windows_exporter.exe: error: unknown long flag '--collector.process.iis', try --help
Tested fix and working on the commandline and using a config file.
> Fix collector.process.iis flag

- pkg/collector/cpu/cpu.go
- tools/e2e-output.txt
Ref: https://en.wiktionary.org/wiki/privileged
> Fix typo "Privileged"

- pkg/collector/handler.go
Refactor in 0711268d3c3025b5b6ed49b3862264b7e7600bec introduced #1389, where the `collect[]=` parameter is being ignored, preventing users from filtering metrics.
This change ensures the collector filter is applied.
> fix: Apply query filter to metrics

- .editorconfig
- .gitignore
- README.md
- installer/build.ps1
- installer/windows_exporter.wxs
> installer: Disable Windows Firewall Exception by default. Can be re-enabled with ADD_FIREWALL_EXCEPTION=yes

- pkg/collector/logical_disk/logical_disk.go
Added label volume_name using WIN32_LogicalDisk to logical_disk collector
Example metric with new label:
HELP windows_logical_disk_free_bytes Free space in bytes, updates every 10-15 min (LogicalDisk.PercentFreeSpace)
TYPE windows_logical_disk_free_bytes gauge
windows_logical_disk_free_bytes{volume="C:",**volume_name**="Local Disk"} 1.9264438272e+10
windows_logical_disk_free_bytes{volume="E:",**volume_name**="EXCH9-E"} 3.5105275904e+10
> Add label volume_name to logical_disk collector

- .github/workflows/release.yml
Should fix that error: https://github.com/prometheus-community/windows_exporter/actions/runs/8976365174/job/24653073353
> fix: release builds

- .github/workflows/lint.yml
- .github/workflows/release.yml
- Dockerfile
- Makefile
- README.md
Fixes #1476 
This PR introduce the image push to dockerhub and quay.io. 
~~There is a new image flavor (hostprocess image) which is designed for hostprocesses. It works on any OS.~~ - It's only possible to build that image with buildkit which is not available under Windows
Additionally, the release pipelines now includes pushes from master branch. The release process will now continuously tested and we are able to gain faster feedback from the community.
I'm expected some push error after merge, since I'm not a makefile pro.
> Add: push docker images to dockerhub and quay.io

- pkg/collector/scheduled_task/scheduled_task.go
Based on: https://github.com/influxdata/telegraf/blob/2de80263d5875531b5c39eb63c85b20109a35799/plugins/inputs/win_wmi/query.go#L77
Fixes #1425
> scheduled_task: Move OLE connection to collect function

- .github/workflows/release.yml
- Makefile
- README.md
- installer/build.ps1
- installer/windows_exporter.wxs
Fixes #1313 
Thats a workaround until process collector uses PDH calls to gather the data. Tested on a Windows Server 2022
> Enable process V1 performance counters by default

- .github/workflows/release.yml
ref: https://github.com/prometheus-community/windows_exporter/actions/runs/9047202056/job/24858834502
> fix: release build again

- .github/workflows/release.yml
- Makefile
- README.md
We don't know the robots account name if quay,io.
I asked in Slack https://cloud-native.slack.com/archives/C01AUBA4PFE/p1715422584716549 but this block us to publish and release a new RC.
> Remove push to quay.io

- docs/collector.remote_fx.md
- pkg/collector/remote_fx/remote_fx.go
I've added FECRate, LossRate, and RetransmissionRate metric to remote_fx_net.   These metrics help determine connection health and should be included.
> Add new RemoteFX network metrics

- exporter.go
Hopefully this will mitigate or resolve #724
> feat: allow setting of exporter process priority

- docs/collector.service.md
- pkg/collector/service/service.go
Ref: #1458 (@paologallinaharbur needs to confirm this as fix)
The old service collector via WMI query doesn't perform well. 
The alternative approach (using the API direct) is an better improvement, however it needs time, because is asks each single service about state and configuration. That doesn't scale well. Additionally, admin permissions is mandatory. 
I introduce a V2 collector here, because it's an breaking change in terms of metrics. (labels are different and information are omit)
The code based on https://github.com/DataDog/datadog-agent/blob/afbd8b6c87939c92610c654cb07fdfd439e4fb27/pkg/util/winutil/scmmonitor.go#L59
WMI:
windows_exporter_collector_duration_seconds{collector="service"} 0.4285152
API:
windows_exporter_collector_duration_seconds{collector="service"} 0.3175442
V2: …
> Service V2 collector

- README.md
The ghcr.io and the docker.io image are inverted with their description
> fix(README.md): Corrected image links

- pkg/collector/dfsr/dfsr.go
- pkg/collector/exchange/exchange.go
- pkg/collector/mssql/mssql.go
- pkg/collector/textfile/textfile.go
> mssql: fix nil panic, if YAML file is used a configuration

- pkg/collector/terminal_services/terminal_services.go
> terminal_services: Avoid duplicate metrics by add session_id

- README.md
> chore: Update TEXTFILE_DIRS description in README

- pkg/collector/cache/cache.go
> cache: fix windows_cache_copy_read_hits_total metric

- README.md
- docs/collector.cpu_info.md
- pkg/collector/cpu_info/cpu_info.go
- tools/e2e-output.txt
- tools/end-to-end-test.ps1
- tools/promtool.ps1
```
windows_cpu_info{architecture="9",description="AMD64 Family 25 Model 33 Stepping 2",device_id="CPU0",family="107",name="AMD Ryzen 9 5900X 12-Core Processor"} 1
windows_cpu_info_core{device_id="CPU0"} 12
windows_cpu_info_enabled_core{device_id="CPU0"} 12
windows_cpu_info_l2_cache_size{device_id="CPU0"} 6144
windows_cpu_info_l3_cache_size{device_id="CPU0"} 65536
windows_cpu_info_logical_processor{device_id="CPU0"} 24
windows_cpu_info_thread{device_id="CPU0"} 24
```
> cpu_info: Extend processor information

- .github/workflows/pr-check.yaml
- pkg/collector/collector.go
Fixes: #1458
Ref: https://github.com/prometheus-community/windows_exporter/issues/1350#issuecomment-2324325364
> collector: Skip collecting performance data if the enabled collectors don't request any.

- exporter.go
- pkg/collector/cpu/const.go
- pkg/collector/cpu/cpu.go
- pkg/utils/collector.go
interested user can enable that feature with env var `WINDOWS_EXPORTER_PERF_COUNTERS_ENGINE=pdh`
> cpu: Fetch performance counter via PDH.dll via feature toggle. (off by default)

- pkg/collector/dfsr/dfsr.go
- pkg/collector/exchange/exchange.go
- pkg/collector/filetime/filetime.go
- pkg/collector/mscluster/mscluster.go
- pkg/collector/mssql/mssql.go
Unify the name of flags:
| Old | New |
|--------|--------|
| `--collectors.dfsr.sources-enabled` | `--collector.dfsr.sources-enabled` |
| `--collectors.exchange.list` | `--collector.exchange.list` |
| `--collectors.exchange.enabled` | `--collector.exchange.enabled` |
| `--collectors.filetime.file-patterns` | `--collector.filetime.file-patterns` |
| `--collectors.mscluster.enabled` | `--collector.mscluster.enabled` | 
| `--collectors.mssql.class-print` | `--collector.mssql.class-print` | 
| `--collectors.mssql.classes-enabled` | `--collector.mssql.classes-enabled` |
> *: replace `--collectors.[name].*` with `--collector.[name].*` flags (click PR number for more information)

- internal/collector/adcs/adcs.go
- internal/collector/process/const.go
- internal/collector/process/process.go
To enable `Process V2` collector support, set `engine=pdh` to msi installer.
> process: Implement PDH collector and add support for Process V2

- README.md
Probably the collector got renamed from `updates` to `update` at some point but the link in the README was forgotten.
> chore(docs): fix link to update collector

- README.md
- docs/collector.logon.md
- internal/collector/logon/logon.go
- internal/headers/secur32/secur32.go
- internal/headers/secur32/secur32_test.go
- internal/headers/secur32/types.go
This PR reworks the logon collector.
It replaces the slow WMI query with Win32 API syscalls. Instead expose the amount of session types, each logon session is exposes.
The `windows_logon_logon_type` metric as been replaced by `windows_logon_session_logon_timestamp_seconds`.
The `windows_logon_session_logon_timestamp_seconds` metric hold each single session on each system. As value, the logon time is used. Username and Domain name is exposed as well. 
The `status` label from `windows_logon_logon_type` metric has been renamed to `type` and matches the case from the Windows documentation. `remote_interactive` -> `RemoteInteractive`
If running as SYSTEM user, system session will be exposed as well.
The collect time has been reduced by 90%+
---
``` …
```
> logon: BREAKING: replace wmi query by Win32 API calls and expose detailed logon sessions. (click PR for more information)

- docs/collector.update.md
To check if the _Windows Update_ service is running it is useful to run the `Get-Service` cmdlet, therefore it's good to know the actual service _name_ (as opposed to the _display name_ that is used e.g. by the Services snap-in).
For example
```
Get-Service wuauserv
```
will show the current status of the update service.
Additionally, this commit modifies several *s* to be lowercase, as the full *display name* of the corresponding service is "Windows Update", not "Windows Update Service" - at least on all the Windows versions I was able to check.
> docs: add actual Windows Update service name

- README.md
Adds a line which explains the log.file argument, and explains how the [MSI installer adds an argument which defaults this to eventlog](https://github.com/prometheus-community/windows_exporter/blob/ce2df385a6f994889b70d7ea169df7b04dc83320/installer/files.wxs#L16).
Description taken from log flag setup under [internal/log/flag/flag.go](https://github.com/prometheus-community/windows_exporter/blob/ce2df385a6f994889b70d7ea169df7b04dc83320/internal/log/flag/flag.go#L27)
> docs: Add log.file argument to README

- docs/collector.textfile.md
`textfile` collector was disabled by default in #1560 but the collector documentation was not updated to match.
> docs: Update textfile collector defaults inclusion

- .github/workflows/pr-check.yaml
- exporter.go
- internal/collector/adcs/adcs.go
- internal/collector/adfs/adfs.go
- internal/collector/cache/cache.go
- internal/collector/cpu/cpu.go
- internal/collector/dfsr/dfsr.go
- internal/collector/dhcp/dhcp.go
- internal/collector/exchange/exchange.go
- internal/collector/logical_disk/logical_disk.go
- internal/collector/memory/memory.go
- internal/collector/net/net.go
- internal/collector/process/process.go
- internal/testutils/testutils.go
- internal/toggle/main.go
- internal/utils/collector.go
Ref: https://github.com/prometheus-community/windows_exporter/issues/1350#issuecomment-2466181287
> feat: add perfcounter.engine CLI option as alternative to WINDOWS_EXPORTER_PERF_COUNTERS_ENGINE env

- internal/collector/smb/const.go
- internal/collector/smb/smb.go
- internal/collector/smbclient/const.go
- internal/collector/smbclient/smbclient.go
ref https://github.com/prometheus-community/windows_exporter/issues/1350
> smb: refactor collector

- internal/collector/mscluster/mscluster.go
- internal/collector/mscluster/mscluster_cluster.go
- internal/collector/mscluster/mscluster_network.go
- internal/collector/mscluster/mscluster_node.go
- internal/collector/mscluster/mscluster_resource.go
- internal/collector/mscluster/mscluster_resourcegroup.go
Ref: https://github.com/prometheus-community/windows_exporter/issues/1743
> mscluster: fix cluster and network sub collectors

- cmd/windows_exporter/main.go
- installer/files.wxs
- installer/main.wxs
- internal/log/flag/flag.go
- internal/log/logger.go
fixes https://github.com/prometheus-community/windows_exporter/pull/1702#issuecomment-2492833757
> fix: use log.file=eventlog as default value, if running as windows service

- internal/collector/net/net.go
- internal/collector/textfile/textfile.go
- internal/collector/textfile/textfile_test_test.go
fix: https://github.com/prometheus-community/windows_exporter/issues/1748
> textfile: set windows_exporter_collector_success to 0, if an errors occurs

- pkg/collector/collect.go
fix https://github.com/prometheus-community/windows_exporter/issues/1748
> collector: don't fail if perf counters are empty.

- docs/collector.system.md
- internal/collector/system/system.go
- tools/e2e-output.txt
Fixes #1783 
Renaming metric to clarify the value
> system: BREAKING rename `windows_system_system_up_time` to `windows_system_boot_time_timestamp_seconds`

- internal/collector/hyperv/hyperv_hypervisor_root_virtual_processor.go
- internal/collector/hyperv/hyperv_hypervisor_virtual_processor.go
% Guest Idle Time was removed in Server 2025
Ref: https://github.com/prometheus-community/windows_exporter/issues/1782#issuecomment-2508349337
> hyperv: Removed `% Guest Idle Time` performance counters (introduced in 0.30.0-beta.4)

- internal/collector/mssql/mssql_sql_errors.go
- internal/collector/mssql/mssql_sql_stats.go
> mssql: fix not collecting sql errors

- docs/collector.dhcp.md
- docs/collector.net.md
- docs/collector.netframework.md
- internal/collector/dhcp/dhcp.go
- internal/headers/dhcpsapi/dhcpsapi.go
- internal/headers/dhcpsapi/dhcpsapi_test.go
- internal/headers/dhcpsapi/types.go
- internal/headers/win32api/types.go
Provide more detailed DHCP scope stats.
```
windows_dhcp_acks_total 0
windows_dhcp_active_queue_length 0
windows_dhcp_conflict_check_queue_length 0
windows_dhcp_declines_total 0
windows_dhcp_denied_due_to_match_total 0
windows_dhcp_denied_due_to_nonmatch_total 0
windows_dhcp_discovers_total 0
windows_dhcp_duplicates_dropped_total 0
windows_dhcp_failover_bndack_received_total 0
windows_dhcp_failover_bndack_sent_total 0
windows_dhcp_failover_bndupd_dropped_total 0
windows_dhcp_failover_bndupd_pending_in_outbound_queue 0
windows_dhcp_failover_bndupd_received_total 0
windows_dhcp_failover_bndupd_sent_total 0
windows_dhcp_failover_transitions_communicationinterrupted_state_total 0
windows_dhcp_failover_transitions_partnerdown_state_total 0 …
```
> dhcp: add dhcp scope stats

- .github/workflows/release.yml
- cmd/windows_exporter/main.go
> config: multiple web.listen-address args results into an error, if --config.file is defined.

- cmd/windows_exporter/0_service.go
> fix: Support running as Windows Service within containers

- docs/collector.update.md
This PR fixes the metric names in the `docs/collector.update.md` file. The documentation previously used the prefix `updates`, which doesn't match the actual exported metrics. This update aligns the docs with the current code.
- Corrected metric names:
- `windows_updates_pending_info` ➝ `windows_update_pending_info`
- `windows_updates_scrape_query_duration_seconds` ➝ `windows_update_scrape_query_duration_seconds`
- `windows_updates_scrape_timestamp_seconds` ➝ `windows_update_scrape_timestamp_seconds`
- Updated example output
- Updated `windows_update_pending_info` description (grammar)
- Added a note to clarify the mismatch between CLI flags and metric prefix
Flag names (e.g., `--collector.updates.online`) were intentionally left unchanged to match the collector name in the CLI interface. …
> docs: Fix incorrect metric prefix in update collector documentation

- README.md
> docs: remove config.file.insecure-skip-verify

- docs/collector.exchange.md
- internal/collector/exchange/exchange_autodiscover.go
- internal/collector/exchange/exchange_availability_service.go
- internal/collector/exchange/exchange_transport_queues.go
> exchange: fix The specified counter could not be found

- internal/collector/update/update.go
Currently properties of `update.Config` are not exported so they cannot be read from yaml config file.
This change also make it possible to configure these fields when using this exporter in alloy https://github.com/grafana/alloy/issues/3660
- fixes #
> update: export properties so that they can be read from yaml file

- internal/collector/logical_disk/logical_disk.go
The `logical_disk` collector may fail if a volume is recognized by Windows but not mounted.  All `logical_disk` metrics will then not be emitted.
In this case, the error logged is something like:
```
source=collect.go:212 msg="collector logical_disk failed after 42.6338ms, resulting in 0 metrics"
err="failed to get volumes: GetVolumePathNamesForVolumeName: The system cannot find the file specified."
```
This change makes it so the failure from `GetVolumePathNamesForVolumeName` of `ERROR_FILE_NOT_FOUND` is not a hard-stop (will just be skipped), and the gathering of metrics for other volumes will continue.
This scenario can happen when e.g. an uninitialized volume is plugged into the computer.
n/a
n/a
n/a
> logical_disk: skip unmounted volumes

- internal/collector/mssql/types.go
PR changes the key from `Value` to `PatchLevel`, from which it reads in the `mssql` collector.
- fixes #2107 
Change the value of the `patch` label in `windows_mssql_instance_info`.
> mssql: fix incorrect patch version in windows_mssql_instance_info
