prometheus-community/windows_exporter

collectors/perf.go
=> Perf: Make exclusion of _Total label hardcoded

README.md, exporter.go
=> Change default port to 9182

collector/iis.go, collector/logical_disk.go, collector/os.go, collector/wmi.go, exporter.go
=> make enabled collectors configurable (based on code from node_exporter)

collector/cs.go, collector/os.go, collector/system.go
Was looking over the bosun WMI collectors a bit and thought this might be useful.
=> os: expose Win32_ComputerSystem and Win32_PerfRawData_PerfOS_System

exporter.go
@carlpett Will this work, with respect to #25 ?
=> exporter: add /health endpoint. fixes #25

collector/net.go, collector/net_test.go, exporter.go
=>  add network collector

appveyor.yml
=> appveyor: build using promu to embed branch and revision info into binary

README.md, exporter.go
=> Set default collectors and update documentation

README.md, collector/service.go, exporter.go
=> Add Win32_Service collector

collector/service.go
This will make sure will always expose all the states/start modes that a service can be in, as discussed in #55 after closing.
However, implementing this has made me reconsider the discussion in the original pull-request regarding if this should be enabled by default, since it seems I made some miscalculation regarding the number of metrics. I get ~2500 on my machine, not ~400. 
This might still not be such a big deal (our Prometheus server currently ingests ~700k metrics/s, and I'm guessing it wouldn't be called a "big" installation by the core team), but still might warrant taking the discussion again. @martinlindhe, what do you think?
=> Always expose all possible service states/start modes

installer/wmi_exporter.wxs
=> Ignore failures to setup the firewall exception during installation

README.md, collector/vmware.go
This adds a Vmware collector as suggested in #80.
=> Add Vmware collector

exporter.go, vendor/github.com/StackExchange/wmi/README.md, vendor/github.com/StackExchange/wmi/swbemservices.go, vendor/github.com/StackExchange/wmi/wmi.go, vendor/github.com/go-ole/go-ole/variant_s390x.go, vendor/vendor.json
=> Fix memory leak

README.md, collector/ad.go
So, I started this way back in November, but then priorities were shifted and the branch has been collecting dust for a while. But I had an opportunity to finish it up today, so here it is. 
Fixes #43
=> First implementation of AD collector

exporter.go
Fixes #91, as a temporary measure.
@martinlindhe I started looking at just changing the flags, but of course nothing is as simple as could be expected... I'll create a new issue to discuss it.
=> Add hint in usage about quoting flags in powershell

README.md, collector/service.go
Follow up to my comment in issue #105 
* Added flag to filter services (like the one for the process collector).
* Added example for said flag in README.md
=> Service Collector Filter Flag

README.md
=> README: add an example for -collector.process.processes-where, fixes #105

.promu.yml, Makefile, appveyor.yml
=> Add build.binary to promu config

.gitignore, collector/iis.go
This pull request fixes issue described here: https://github.com/martinlindhe/wmi_exporter/issues/131
=> fix: IIS Collector fails, when Application has more than one worker processes

README.md, collector/tcp.go
For retrieving metrics about TCP connections.
=> Add TCP collector

exporter.go
=> Add process_start_time_seconds for the exporter itself

collector/system.go
=> Fix wrong metric types in system collector, improve help-strings

collector/service.go
Fixes #171.
On my test system this results in 2966 new series, so the warning about not applying a filter on the WQL is more true than ever...
=> Add status metric for service-collector

collector/mssql.go
=> Strip special chars from instance names

contrib/console_templates/wmi-overview.html
=> add wmi-overview console template

Gopkg.lock, collector/textfile.go, vendor/github.com/dimchansky/utfbom/utfbom.go
See https://github.com/martinlindhe/wmi_exporter/pull/293#discussion_r237579386 for a little background - this is just a slight simplication made possible by the newer version of `github.com/dimchansky/utfbom`
=> textfile collector: updating utfbom dependency and simplifying code

docs/collector.textfile.md
Added a practical example for textfile collector using a Powershell snippet that generates a valid file.
=> Added an example for textfile collector

docs/collector.service.md
Just contributing some useful examples that I have made using for monitoring Microsoft SQL Server instances.
=> adding windows service example alerts/queries

collector/logical_disk.go
This PR adds the metrics created in #329 with corrected metric names.
=> Add logical_disk latency metrics

docs/README.md, docs/collector.cpu.md, docs/collector.logical_disk.md, docs/collector.memory.md, docs/collector.net.md, docs/collector.system.md
Add missing documentation for a number of collectors. Documentation for metrics is largely sourced from the linked MSDN articles.
Should resolve #367 and contribute towards solving #298. I plan to submit additional PR(s) to document the remaining collectors.
=> Add collector documentation

docs/collector.os.md, docs/collector.tcp.md
Add documentation for the `os` and `tcp` collectors.
=> Additional collector documentation

collector/net.go, docs/collector.net.md
Bandwidth estimate for an interface may decrease or increase
=> Set current_bandwidth to gauge type

README.md
msiexec install example for older windows versions
=> Another msiexec install example

tools/collector-generator/New-Collector.ps1
There was an extra parenthesis at the end of line no 23
=> Fixed bug in script

exporter.go
This PR adds a flag to limit concurrent scrapes, `--max-requests <n>`. Any requests coming in while there are already `n` scrapes in progress get a 503.
I picked a default of 5 somewhat arbitrarily, but most systems start to have problems servicing even two or three concurrent requests with heavier WMI queries. Given our 10 second default timeout, this default would allow for one scrape every two seconds, which is quite a bit more frequent than what is normally recommended.
=> Add option to limit concurrent requests

tools/collector-generator/collector.template
This should bring the generated code up to date with the rest of the code base
=> Update collector generator template

collector/collector.go
=> Check that collectors given on --collectors.enabled exist before trying to construct them

collector/dhcp.go
=> Fix DHCP helptext

docs/collector.memory.md
=> Remove cs metrics from memory collector docs

README.md, exporter.go
implements #139 
This is heavily inspired by the node exporter: https://github.com/prometheus/node_exporter/pull/699
=> Add URL filter for collectors

README.md, exporter.go
=> Fix exporter failing to start without config flag

README.md, installer/windows_exporter.wxs
Installation on versions previous to Win7/Server2008R2 will now fail.
Fixes #611
Ref
https://wixtoolset.org/documentation/manual/v3/xsd/wix/package.html
https://docs.microsoft.com/en-us/windows/win32/msi/released-versions-of-windows-installer
=> Clarify supported versions of Windows

README.md, collector/collector.go, collector/collector_test.go, collector/dfsr.go, collector/mssql.go, collector/smtp.go, docs/README.md, docs/collector.dfsr.md
Implements DFSR collectors, though no metric documentation is present yet. Will resolve #666 when merged.
@mjozefcz are you comfortable testing this PR, or would you like me to provide some build instructions?
=> Add DFSR collectors

collector/dfsr.go, docs/collector.dfsr.md
Reviewing these metrics has made me realise how sloppy my initial implementation was :disappointed:
@bds006 this should resolve your error with the empty metric descriptions, but keep in mind these metrics are still untested so there may be other bugs for you to discover.
Resolves #707
=> Add missing dfsr metric descriptions

collector/dfsr.go, docs/collector.dfsr.md
Resolves remaining errors with DFSR collector metric names. This has been tested by @bds006 and resolves #715
=> Ensure dfsr collector metric names are unique

README.md, collector/cache.go, docs/collector.cache.md
Implements collector for Windows Cache. This is using the commits provided by @wbagdon provided in #455.
Due to the age of the PR, I've rebased the commits from current master and pushed to a new branch.
=> Cache collector

README.md, exporter.go, go.mod, go.sum
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Update web config file flag to match upstream

README.md
=> Example - Using [defaults] with `--collectors.enabled` argument

docs/collector.memory.md
Changed 'Yes' to 'No' to reflect current state of collectors enabled by default.
Fixes #777
=> Fixes #777 

collector/os.go, tools/e2e-output.txt
=> Fix typo: process_memory_limit_bytes

collector/thermalzone.go
See https://github.com/prometheus-community/windows_exporter/issues/816#issuecomment-898065629 for context.
=> Thermalzone: return error on empty result

README.md
Signed-off-by: Austin D. Krauza <krauza.austin@gmail.com>
=> Update repository readme with ADCS documentation link

collector/cpu.go, docs/collector.cpu.md, tools/e2e-output.txt
=> Ensure CPU time description matches `mode` flag

.github/workflows/ci.yml, tools/end-to-end-test.ps1, tools/promtool.ps1
Required to keep container image (with "latest" tag) up to date. Will
also ensure the master branch is healthy after PR merges.
Resolves #940
=> Run CI on pushes to master branch

docs/collector.container.md
@carlpett  @breed808  Sorry for a typo error in container docs. Please review it.
=> fix: typo of container docs

collector/textfile.go
This change affects processing of single files with duplicate metrics.
Single files with duplicate metrics will be skipped, with no metrics being
collected and exposed by the exporter.
Previous duplicate metric processing across multiple files remains
unchanged (all files skipped, collector returns error).
Resolves #448
=> Skip processing files with duplicates metrics

go.mod, go.sum
Quick try to bump the lib /x/sys and using the latest "stable" version 0.1.0 instead of 0.0.0-snapshot
=> Try to bump /x/sys to the current stable version to fix IsWindowsService()

collector/os.go
=> fix: Continue os collection on missing page file

docs/collector.scheduled_task.md
=> Add scheduled_task flag examples

docs/collector.diskdrive.md
Signed-off-by: Brandon Kauffman <bck01215@gmail.com>
=> Remove Bad Comment

docs/collector.iis.md, docs/collector.mssql.md
This PR is related with the [following issue](https://github.com/prometheus-community/windows_exporter/issues/1143)
=> Update docs for mssql and iis

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/spelling.yml, .promu.yml, exporter.go, go.mod, go.sum
Use the new exporter-toolkit landing page generator feature.
* Update Go to 1.20.
* Update promu to 0.14.0.
=> Use new landing page generator

collector/net.go, docs/collector.net.md, tools/e2e-output.txt
=> feat: Add output_queue_length metric to net collector

collector/adfs.go, docs/collector.adfs.md
=> fix!: Fix jtw -> jwt ADFS spelling error

README.md
=> feat(doc): Document Powershell v7.3 argument parsing

collector/init.go, collector/nps.go, collector/nps_test.go, docs/README.md, docs/collector.nps.md
The PR add the a NPS collector of server data from this 2 classes:
- Win32_PerfRawData_IAS_NPSAuthenticationServer 
- Win32_PerfRawData_IAS_NPSAccountingServer
=> NPS(feature): add nps collector

log/logger.go
=> Fix panic with log.file=eventlog

docs/collector.tcp.md
=> fix(docs): Set correct TCP reset description

collector/service.go
=> fix: Fix spelling error in service collector

Dockerfile.cross
With this dockerfile, you could build docker images on any plattform for Windows, including on linux/arm64 (Mac MX)
=> Add cross OS Dockerfile

MAINTAINERS.md
@jkroepke I'll let you do the honours for reviewing and approving :)
=> feat: Add jkroepke to maintainers

pkg/collector/process/process.go
When using process with config this was not being set.
=> Add check for enable worker process so it is properly set.

installer/windows_exporter.wxs
=> Remove old event source registry key

docs/collector.os.md
Added a useful query to show the memory being used by an instance in percentage
Signed-off-by: Isai Alejandro <isai_mendoza@outlook.com>
=> Added useful query for memory usage

exporter.go
I believe this has a good chance of fixing https://github.com/prometheus-community/windows_exporter/issues/1373 and https://github.com/prometheus-community/windows_exporter/issues/1374 and https://github.com/prometheus-community/windows_exporter/issues/1371.
=> add call to set perf counter query

docs/collector.cpu_info.md, docs/collector.cs.md, pkg/collector/cpu_info/cpu_info.go, pkg/collector/cs/cs.go, tools/e2e-output.txt
Ref: https://en.wiktionary.org/wiki/labelled
=> Fix typo "Labelled"

pkg/collector/os/os.go
=> Restore Windows 2012 support.

.gitignore, Makefile, exporter.go, winres/winres.json
I'm using github.com/tc-hib/go-winres to generate an application manifest to archive a version number on the exe file.
=> Implement a Windows application manifest

exporter.go
=> Ability to disable debug endpoints

installer/windows_exporter.wxs
Fixes #1388
Tested on a Windows 10 system.
=> Do not add "--web.listen-address" to service if default values are provided

pkg/collector/iis/iis.go
=> iis: Add IIS info metric

.github/workflows/release.yml
ref: https://github.com/prometheus-community/windows_exporter/actions/runs/8992184557
=> fix: release builds

exporter.go
=> Remove landing page

go.mod, pkg/collector/os/os.go, pkg/headers/kernel32/kernel32.go
=> Fix timezone caching issues

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yaml, .github/ISSUE_TEMPLATE/question.yaml, .github/dependabot.yml, .github/release.yml, .github/workflows/pr-check.yaml
=> chore: Add label configuration

pkg/collector/cpu/cpu.go
=> fix: CPU Collector % Cx Time mismatch

pkg/headers/wtsapi32/wtsapi32.go
=> terminal_services: Fix "The operation completed successfully." error

pkg/collector/cs/cs.go, pkg/collector/dhcp/dhcp.go, pkg/collector/diskdrive/diskdrive.go, pkg/collector/dns/dns.go, pkg/collector/exchange/exchange.go, pkg/collector/fsrmquota/fsrmquota.go, pkg/collector/hyperv/hyperv.go, pkg/collector/license/license.go, pkg/collector/logical_disk/logical_disk.go, pkg/collector/logon/logon.go, pkg/collector/memory/memory.go, pkg/collector/mscluster_cluster/mscluster_cluster.go, pkg/collector/mscluster_network/mscluster_network.go, pkg/collector/mscluster_node/mscluster_node.go, pkg/collector/mscluster_resource/mscluster_resource.go, pkg/collector/mscluster_resourcegroup/mscluster_resourcegroup.go, pkg/collector/msmq/msmq.go, pkg/collector/mssql/mssql.go, pkg/collector/net/net.go
=> *: Collector API cleanup 2

.github/workflows/pr-check.yaml, installer/windows_exporter.wxs
=> installer: do not enable V1 counters by default

README.md, docs/example_config.yml, pkg/types/const.go, tools/end-to-end-test.ps1
=> textfile: disable collector by default

config.yaml, pkg/collector/exchange/exchange.go
=> exchange: enable all collectors as default

pkg/collector/process/process.go
=> process: fix Access is denied errors

.github/workflows/stale-close.yml
Close stale issues to keep the amount of issue in a clean state.
=> chore: close stale issues

.github/workflows/pr-check.yaml, README.md
=> chore(docs): firewall not enabled by default

docs/collector.service.md, pkg/collector/service/service.go, tools/e2e-output.txt
=> service: fix label name in `windows_service_state`

README.md, docs/collector.filetime.md, go.mod, go.sum, pkg/collector/collector.go, pkg/collector/config.go, pkg/collector/filetime/filetime.go, pkg/collector/filetime/filetime_test.go, pkg/collector/map.go, pkg/headers/kernel32/kernel32.go
=> filetime: add collector

pkg/collector/prometheus.go
ref: https://github.com/prometheus-community/windows_exporter/issues/1641#issuecomment-2378534379
=> collector: change log level to info for succeeded

pkg/collector/service/service.go
=> service: [0.27.x] fix panic with NewWithConfig code path

pkg/collector/service/service.go
=> service: [0.28.x] fix panic with NewWithConfig code path

README.md, docs/collector.update.md, pkg/collector/collector.go, pkg/collector/config.go, pkg/collector/map.go, pkg/collector/updates/updates.go, pkg/collector/updates/updates_test.go
=> updates: add windows update collector

pkg/types/regexp.go
Ref: https://github.com/grafana/alloy/issues/1845#issuecomment-2402522821
=> *: [0.27] don't exclude resources, if exclude option is empty. 

exporter.go, pkg/collector/collector.go
=> fix: fail, if unknown collector is defined in enabled list

internal/collector/tcp/tcp_test.go, internal/perfdata/v1/collector.go, internal/perfdata/v1/perflib.go
=> tcp: fix panic on collector

docs/collector.time.md, internal/collector/service/service_test.go, internal/collector/time/const.go, internal/collector/time/time.go, internal/collector/time/time_test.go, internal/collector/vmware/const.go, internal/collector/vmware/vmware.go
=> time: refactor collector

internal/collector/terminal_services/const.go, internal/collector/terminal_services/terminal_services.go, internal/collector/terminal_services/terminal_services_test.go, internal/headers/wtsapi32/wtsapi32.go, internal/mi/callbacks.go, internal/mi/session.go
Ref https://github.com/prometheus-community/windows_exporter/issues/1350
=> terminal_services: refactor collector

internal/collector/logical_disk/logical_disk.go, internal/collector/mssql/mssql_access_methods.go, internal/collector/mssql/mssql_buffer_manager.go, internal/collector/mssql/mssql_database.go, internal/collector/mssql/mssql_locks.go, internal/perfdata/collector.go
=> logicaldisk: fix base counter values

internal/collector/logical_disk/logical_disk.go
Resolves bugs like 
Access denied
on logical_disk collector
=> logical_disk: Get Volume ID for NTFS Volume Mounts

internal/collector/mssql/mssql.go
fix https://github.com/prometheus-community/windows_exporter/issues/1748
=> mssql: set windows_exporter_collector_success to 0, if errors occurs

internal/collector/vmware/const.go
fixes https://github.com/prometheus-community/windows_exporter/issues/1788
=> vmware: fix memory collector

.run/all.run.xml, internal/collector/iis/iis_app_pool_was.go, internal/collector/iis/iis_web_service_cache.go
=> iis: Fix label for Default Web Site

internal/collector/performancecounter/performancecounter.go, internal/collector/performancecounter/performancecounter_test_test.go, internal/collector/vmware/vmware.go
=> performancecounter: fix panic with counter names having brackets

internal/collector/netframework/netframework.go
=> netframework: add --collector.netframework.enabled CLI flag

internal/collector/net/net.go
=> net: fix sanitize # on the nic label for windows_net_nic_address_info

installer/main.wxs, internal/config/config.go
=> config: deprecate remote http configuration

cmd/windows_exporter/main.go
=> fix: process priority setting

internal/collector/service/service.go
=> service: re-use buffer for return all services

installer/main.wxs
=> installer: force close application on uninstall

internal/collector/process/process.go, internal/collector/process/process_v1.go, internal/collector/process/process_v2.go, internal/pdh/collector.go
=> process: negative values with windows_process_start_time

installer/build.ps1, installer/main.wxs
=> installer: add validation for EXTRA_FLAGS

internal/collector/netframework/netframework_clrexceptions.go, internal/collector/netframework/netframework_clrinterop.go, internal/collector/netframework/netframework_clrjit.go, internal/collector/netframework/netframework_clrloading.go, internal/collector/netframework/netframework_clrlocksandthreads.go, internal/collector/netframework/netframework_clrmemory.go, internal/collector/netframework/netframework_clrremoting.go, internal/collector/netframework/netframework_clrsecurity.go, internal/collector/netframework/netframework_test.go
=> netframework: fix MI_RESULT_INVALID_QUERY

.github/workflows/release.yml
=> fix: sign binaries

internal/collector/cs/cs.go, tools/e2e-output.txt
=> cs: fix metric description

internal/collector/time/time.go
=> time: fix panic if counters aren't present

.github/workflows/lint.yml, docs/collector.physical_disk.md
=> docs: fix physical_disk docs

cmd/windows_exporter/0_service.go
=> fix: log to the Windows temp directory if of service detection failures.

.github/workflows/release.yml
=> ci: fix checksum

internal/collector/terminal_services/terminal_services.go
=> terminal_services: fix panic in collect

README.md
=> docs: added examples for alternative installer dir

go.mod, go.sum
=> fix: update dependencies

.github/workflows/pr-check.yaml, .github/workflows/release.yml, README.md
=> chore: add quay.io registry

internal/collector/hyperv/hyperv.go, internal/collector/hyperv/hyperv_dynamic_memory_balancer.go, internal/collector/hyperv/hyperv_dynamic_memory_vm.go, internal/collector/hyperv/hyperv_hypervisor_virtual_processor.go
=> hyperv: fix Windows Server 2016 compatibility

docs/collector.net.md, internal/collector/net/net.go, tools/e2e-output.txt, tools/end-to-end-test.ps1
=> net: move net IP addresses from `windows_net_nic_info` to `windows_net_nic_address_info` and introduce mac addresses

internal/collector/os/os.go
=> fix: return Windows 11 as product name, if build number is >= 22000

.github/workflows/container_description.yml
=> chore: Add quay.io readme

.github/ISSUE_TEMPLATE/question.yaml
=> chore: Update question issue template

internal/collector/service/service.go
=> service: fix windows.EnumServicesStatusEx reports buffer too small

docs/collector.net.md, internal/collector/net/net.go, internal/collector/net/types.go, tools/e2e-output.txt, tools/end-to-end-test.ps1
=> net: expose operation status of nic

internal/collector/mssql/mssql.go, internal/collector/mssql/mssql_access_methods.go, internal/collector/mssql/mssql_availability_replica.go, internal/collector/mssql/mssql_buffer_manager.go, internal/collector/mssql/mssql_database.go, internal/collector/mssql/mssql_database_replica.go, internal/collector/mssql/mssql_general_statistics.go, internal/collector/mssql/mssql_locks.go, internal/collector/mssql/mssql_memory_manager.go, internal/collector/mssql/mssql_sql_errors.go, internal/collector/mssql/mssql_sql_stats.go, internal/collector/mssql/mssql_transactions.go, internal/collector/mssql/mssql_wait_stats.go, internal/collector/mssql/types.go
=> mssql: support initial non default instances names

docs/collector.mssql.md, docs/collector.net.md
fixing docs, following #1964
- fixes #1964
- [x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] The PR title has a summary of the changes and the area they affect
=> docs: update for #1964

.github/workflows/pr-check.yaml, internal/pdh/collector.go, internal/utils/counter.go, internal/utils/counter_test.go
=> fix: windows_cpu_processor_utility_total is always 0

internal/collector/update/update.go
| Old | New |
|---|---|
| `--collector.updates.online` | `--collector.update.online` |
| `--collector.updates.scrape-interval` | `--collector.update.scrape-interval` |
This PR adds support for both the deprecated `--collector.updates.*` flags and the new `--collector.update.*` flags in the update collector.
It ensures:
- Users can still use the old flags without breaking existing setups.
- When both old and new flags are provided, the new ones take precedence.
- A clear warning is printed if deprecated flags are used, guiding users to update.
Recent updates standardized the metric prefix to `update`, but the collector flags remained `updates`. To support a cleaner interface while preserving compatibility, this PR introduces new flags and a transition path.
=> update: fix naming flags (renamed `--collector.updates.*` to `--collector.update.*`)  (click PR number for more information)

docs/collector.memory.md
`collector.memory.md` doc has an example that uses the old metric name for `windows_memory_physical_free_bytes`
=> docs: fix metric name in example in collector.memory.md

cmd/windows_exporter/0_service.go, internal/collector/service/service.go
=> service: fix inconsistent values for windows_service_start_mode

cmd/windows_exporter/0_service.go, internal/collector/service/service.go
(cherry picked from commit 3f2633d)
- fixes #
=> fix: Support running as Windows Service within containers [0.30.x]

.golangci.yaml, internal/collector/dfsr/dfsr.go, internal/collector/dhcp/dhcp.go, internal/collector/dns/dns.go, internal/collector/exchange/exchange.go, internal/collector/filetime/filetime.go, internal/collector/hyperv/hyperv.go, internal/collector/iis/iis.go, internal/collector/logical_disk/logical_disk.go, internal/collector/mscluster/mscluster.go, internal/collector/mssql/mssql.go, internal/collector/net/net.go, internal/collector/netframework/netframework.go, internal/collector/performancecounter/types.go, internal/collector/physical_disk/physical_disk.go, internal/collector/printer/printer.go, internal/collector/process/process.go, internal/collector/scheduled_task/scheduled_task.go, internal/collector/service/service.go, internal/collector/smtp/smtp.go, internal/collector/tcp/tcp.go, internal/collector/textfile/textfile.go, internal/collector/time/time.go, internal/config/config.go, pkg/collector/config.go
This PR add an configuration file validation to prevents errors like #2008 
- fixes #2008 
=> feat: Add config file validation

docs/collector.process.md
=> docs: add example about add cmdline to process metrics.

internal/collector/terminal_services/terminal_services.go
=> terminal_services: Expose disconnected sessions agains

docs/collector.exchange.md, internal/collector/exchange/exchange_autodiscover.go, internal/collector/exchange/exchange_availability_service.go, internal/collector/exchange/exchange_transport_queues.go
(cherry picked from commit 3f2633d)
- fixes #2019
=> exchange: fix The specified counter could not be found (#1994)

internal/collector/terminal_services/terminal_services.go
(cherry picked from commit 3f2633d)
- fixes #
=> terminal_services: Expose disconnected sessions agains (#2026)

docs/collector.dns.md, internal/collector/dns/dns.go, internal/collector/dns/types.go, internal/mi/types.go
(cherry picked from commit f0d52678747df11778755bf078d64b7252e23ef7)
- fixes #
=> dns: add enhanced metrics (#1999)

docs/collector.msmq.md
Fix typo in MSMQ documentation.
- fixes #
=> docs: Fix typo

internal/collector/tcp/tcp.go, internal/collector/udp/udp.go, internal/headers/iphlpapi/iphlpapi.go
=> tcp: relax metrics collectos on error

internal/collector/update/update.go
Backport of https://github.com/prometheus-community/windows_exporter/pull/2053
- fixes #
=> update: export properties so that they can be read from yaml file

cmd/windows_exporter/main_test.go
=> chore: fix test

.idea/dictionaries/project.xml, internal/collector/container/container.go, internal/headers/kernel32/job.go, internal/headers/kernel32/types.go
=> container: fix collector

.idea/dictionaries/project.xml, docs/collector.gpu.md, internal/collector/gpu/gpu.go, internal/headers/setupapi/gpu.go, internal/headers/setupapi/gpu_test.go, internal/headers/setupapi/setupapi.go, internal/headers/setupapi/types.go
=> gpu: add info metric about devices

docs/collector.dns.md
Fix typo in the name of the dns subcollector in docs.
=> docs: fix typo in dns docs subcollector name

README.md
=> docs: Clearify Windows Server 2012R2 support

internal/collector/logical_disk/logical_disk.go
(cherry picked from commit f285c3d1e2fa52075b759231ed5e7e73a9002cc6)
- fixes #
=> [0.30] logical_disk: skip unmounted volumes (#2084)

internal/collector/service/service.go
(cherry picked from commit ecd7dcfb0d6d1a268ad4b8c86df8f4879f3f7a5e)
- fixes #
=> [0.30] service: report invalid parameter errors as debug (#2051)

.github/ISSUE_TEMPLATE/bug_report.yaml
=> docs: add note about Server 2012

internal/collector/os/os.go, tools/e2e-output.txt
=> os: missing deprecated metric windows_os_processes

internal/collector/service/service.go, internal/httphandler/httphandler.go, pkg/collector/handler.go
- fixes #2097
- fixes #1959
- fixes #1883
=> fix: add missing concurrency lock

internal/collector/mssql/mssql_access_methods.go, internal/collector/mssql/mssql_buffer_manager.go, internal/collector/mssql/mssql_database.go, internal/collector/mssql/mssql_locks.go
=> mssql: fix ratio based counter

internal/collector/process/process.go, internal/collector/process/process_worker.go, internal/collector/system/system.go, tools/e2e-output.txt
=> system: remove windows_system_boot_time_timestamp_seconds

go.mod, go.sum, internal/collector/filetime/filetime.go
- fixes #
ref: https://github.com/bmatcuk/doublestar/pull/106
=> filetime: support case insensitive matching

internal/collector/process/process_worker.go
=> process: fix `windows_process_start_time_seconds_timestamp` return relative time on Windows Server 2019

.github/workflows/pr-check.yaml
=> docs: allow backport PR title prefix.

.github/workflows/lint.yml, .github/workflows/pr-check.yaml
(cherry picked from commit 0e2d78affee980ca52f7f6a7f498b7e00d20db08)
- fixes #
=> [0.30] docs: allow backport PR title prefix. (#2142)

internal/collector/diskdrive/diskdrive.go
(cherry picked from commit 492f3af31712cb95cf35dcee05466dfe4445ec19)
- fixes #
=> diskdrive: fix not exposing state "Pred Fail" (#2101)

internal/collector/mssql/mssql_access_methods.go, internal/collector/mssql/mssql_buffer_manager.go, internal/collector/mssql/mssql_database.go, internal/collector/mssql/mssql_locks.go
=> [0.30] mssql: fix ratio based counter

internal/collector/os/os.go, tools/e2e-output.txt
(cherry picked from commit d64f1316cae65beda6cb68b9094ab462422a0517)
- fixes #
=> [0.30] os: missing deprecated metric windows_os_processes (#2104)

internal/collector/mssql/types.go
=> [0.30] mssql: fix incorrect patch version in windows_mssql_instance_info

README.md
=> docs: add note about property preferences

README.md, installer/main.wxs
Avoid to create a dummy config file, if a custom file path is set.
If a custom file path is given, it's in the user responsibility to create it earlier.
- fixes #1998 
=> installer: disable config file creation, if CONFIG_FILE is set to a non default location.

cmd/windows_exporter/main.go, pkg/collector/collection.go
=> collector: Add disable flag

go.mod
=> chore: update to go 1.25

.gitignore, installer/main.wxs
=> installer: set failureflag for Windows service

go.mod, go.sum, internal/collector/performancecounter/performancecounter.go, internal/collector/performancecounter/types.go, internal/config/config.go, internal/config/flatten_test.go
=> chore: switch to go.yaml.in/yaml/v3

docs/collector.os.md, internal/collector/os/os.go
=> os: include installation type in Windows version retrieval
